### ISSUE TITLE
[Editor] Glitch when selecting the stream for the first time

### ISSUE THREAD

**Issue by niruhan** [wso2/product-sp#102]
**Description:**
The text box to input values for an attribute in the stream doesn't show when selecting the first stream for the first time

**Affected Product Version:**
v4.0.0-M14

**OS, DB, other environment details and versions:**
Ubuntu 16.04 LTS    

**Steps to reproduce:**
1. Start the editor
2. Copy and paste the following query
@App:name("HelloWorldApp")

define stream CargoStream (weight int);

@info(name='HelloWorldQuery') 
from CargoStream
select weight, sum(weight) as totalWeight
insert into OutputStream;

from OutputStream#log("LOGGER")
select *
insert into temp2;

3. Save the .siddhi file
4. Go to Event Simulator
5. Select HelloWorldApp in Siddhi App Name drop down
6. CargoStream is selected by default. (You can even re-select the CargoStream from drop-down)
The text box to input weight doesn't appear in the first try. When you select another stream it appears. And when you re-select CargoStream after selecting another stream the text box for weight appears.

**Comment by dnwick** [comment]
This is fixed now
