### ISSUE TITLE
ORA-00920: invalid relational operator with Oracle Database

### ISSUE THREAD

**Issue by AnuGayan** [wso2/product-sp#1021]
**Description:**
When starting APIM Analytics solution in the latest update  Stream Processor 4.3.0(APIM Analytics 2.6.0) Above issue is occurring.
This happens due to the query that sent out for the  databse contains a " .. AND true" condition and it doesn't supports in Oracle

**Comment by niveathika** [comment]
Fixed with https://github.com/siddhi-io/siddhi/pull/1329
