### ISSUE TITLE
Editor console is not appearing when new tab is used. 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#103]
**Description:**
Sometimes the editor console does not appear when the console button was pressed, and sometimes the console div space is generated but no console is shown in that. 
E.g.
<img width="914" alt="screen shot 2017-10-25 at 12 50 47 pm" src="https://user-images.githubusercontent.com/3785208/31986550-92f5772c-b986-11e7-91e7-fbfe2c36fd90.png">

**Suggested Labels:**
Bug
Studio

**Suggested Assignees:**
Damith

**Affected Product Version:**
4.0.0-M14

**Comment by dnwick** [comment]
This is fixed in with https://github.com/wso2/carbon-analytics/pull/534
