### ISSUE TITLE
Define stream - without stream field

### ISSUE THREAD

**Issue by Idriel** [wso2/product-sp#1035]
Hi, 
Is it possible to define stream like
define stream (field1 string, field2 string, field3 string) 

Then sometimes when receiving stream, stream does not have let say field3. 
Sometimes some stream does not have eg. Geo location information but would like to have that info when stream contains it inside alarm. 

hot to define stream where json can lack some of the fields?

**Comment by niveathika** [comment]
@Idriel, yes it is possible based on the mapper you use. If it is [JSON mapper](https://siddhi-io.github.io/siddhi-map-json/api/5.0.3/#json-source-mapper), you can use `fail.on.missing.attribute` and set it to false, in that case if an attribute is not present null is passed to that attribute in an event.

**Comment by Idriel** [comment]
Thank you @niveathika 
that will do the trick. :)
