### ISSUE TITLE
Viewer role in Dashboard is not working. 

### ISSUE THREAD

**Issue by ug205** [wso2/product-sp#1038]
**Description:**
As per the documentation[1], the dashboard portal has 2 levels of permissions. One of these permissions is the viewer. The user with this role is only allowed to have read-only access to the dashboard. This role is not working. 

[1] https://docs.wso2.com/display/SP400/Dashboard+Authorization+Configuration

**Affected Product Version:**
WSO2-SP-4.0.0/4.1.0/4.2.0/4.3.0/4.4.0
APIM, IS and EI analytics servers using SP.

**Steps to reproduce:**
1. Add the following configuration to <SP_HOME>/conf/dashboard/deployment.yaml

wso2.dashboard:
  roles:
    viewer:
      - {roleID}

2. Create a user assigning this role.

3. Start dashboard.sh 
(Will give an error under Cannot create property=viewer)

**Comment by lasanthaS** [comment]
Resolved, hence closing.
