### ISSUE TITLE
Styling issues in Run or Debug button

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#104]
**Description:**
Aliment of the Run or Debug button is wrong

<img width="616" alt="screen shot 2017-10-25 at 12 50 33 pm" src="https://user-images.githubusercontent.com/3785208/31986639-db16459a-b986-11e7-8c3f-c23be51a922d.png">

**Suggested Labels:**
Bug
Studio

**Suggested Assignees:**
Damith

**Affected Product Version:**
4.0.0-M14

**Comment by dnwick** [comment]
For me its showing correctly . please see 
![rundebug](https://user-images.githubusercontent.com/9207770/32014733-8f3385d8-b9dc-11e7-9312-0f2179e7ec8a.png) I checked on chrome Version 58.0.3029.81 and firefox 56.0

**Comment by suhothayan** [comment]
this issue is there on Mac 
Chrome 61.0.3163.100

**Comment by suhothayan** [comment]
Cannot see this issue anymore
