### ISSUE TITLE
Enabling sync commit for Kafka sources in Stream Processor 

### ISSUE THREAD

**Issue by ug205** [wso2/product-sp#1054]
**Description:**
Providing an option for Kafka sources to force the 'sync commit' in SP.

**Suggested Labels:**
wso2sp

**Affected Product Version:**
wso2sp

**Comment by ramindu90** [comment]
fixed with https://github.com/siddhi-io/siddhi-io-kafka/commit/b7000742a48386f347ca2afb7ead9de9d0e36ffe
