### ISSUE TITLE
Server hangs with nohup mode

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#110]
**Description:**
When you start either the editor or the worker, it just hangs.
`./bin/worker.sh start`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2sp-4.0.0-M16-SNAPSHOT

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Start the server using `./bin/worker.sh start`

**Related Issues:**

**Comment by suhothayan** [comment]
Fixed hence closing
