### ISSUE TITLE
Find and Replace not properly visible in editor 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#114]
**Description:**
the button is not shown

Shortcuts and buttons are not shown anywhere

<img width="359" alt="screen shot 2017-11-01 at 2 56 12 pm" src="https://user-images.githubusercontent.com/3785208/32268425-0a5fb7e4-bf15-11e7-816e-a0d3fb403b30.png">

**Comment by Anoukh** [comment]
@suhothayan this works fine in my machine. Is it recurring issue in MacOS?

![image](https://user-images.githubusercontent.com/8677511/32299640-4d143eb8-bf7c-11e7-8c95-422d413c722b.png)

**Comment by dnwick** [comment]
@Anoukh this is fixed after suho reported it
