### ISSUE TITLE
Make editor tooltip lighter colour 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#121]
**Description:**
Sometimes the tooltip is not visible as its color is similar to the editor background. 

<img width="693" alt="screen shot 2017-11-01 at 11 19 29 pm" src="https://user-images.githubusercontent.com/3785208/32288886-4fdfe3b6-bf5b-11e7-820d-c1c4e1498b3b.png">

Make it a bit lighter.

**Comment by Anoukh** [comment]
Fixed in PR wso2/carbon-analytics#565
