### ISSUE TITLE
No store annotation listed in auto completion 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#122]
**Description:**
sink and source is added to the autocompletion but not @store 

<img width="459" alt="screen shot 2017-11-01 at 11 25 27 pm" src="https://user-images.githubusercontent.com/3785208/32289230-2c13d590-bf5c-11e7-964b-3550636cac5f.png">

**Comment by Anoukh** [comment]
If we scroll down we can see that store appears in the list

**Comment by suhothayan** [comment]
Not sure why it's not shown on the top of the list ?

**Comment by dnwick** [comment]
Suho do we need the store come up before source and sink ?

**Comment by suhothayan** [comment]
its available hence closing
