### ISSUE TITLE
Remove outdated annotations @import and @export

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#123]
**Description:**
$subject need to be removed in autocompletion 

<img width="459" alt="screen shot 2017-11-01 at 11 25 27 pm" src="https://user-images.githubusercontent.com/3785208/32289304-65b4a644-bf5c-11e7-9c10-86bbbb68d8a2.png">

**Comment by Anoukh** [comment]
Fixed in PR wso2/carbon-analytics#565
