### ISSUE TITLE
Problem launching the stream processor Studio when the actual path of SP_HOME contain white spaces 

### ISSUE THREAD

**Issue by Irindu** [wso2/product-sp#155]
**Description:**
when you download and extract the WSO2 stream processor and navigate to SP_HOME /bin and try to execute ./editor it won't start it give's an error saying can't open and gives a part of the SP_HOME absolute path until it encounters a white space character like this 
![image](https://user-images.githubusercontent.com/19923256/32652864-d822492c-c62b-11e7-94dd-a6160afc0b00.png)

**Suggested Labels:**

Component/Studio
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
4.0.0
**OS, DB, other environment details and versions:**    
Ubuntu Linux 
**Steps to reproduce:**
Download the WSO2 stream processor zip from the following link 
https://github.com/wso2/product-sp/releases
and extract it inside a folder with a name containing white spaces (eg: Stream Processor) and navigate into SP_HOME/bin and try to execute ./editor.sh 

it won't start until you remove the white spaces in the SP_HOME path (eg: Chaning Stream Processor to Stream_Processor or StreamProcessor)

**Related Issues:**

**Comment by grainier** [comment]
Fixed in https://github.com/wso2/product-sp/pull/157
