### ISSUE TITLE
Problem in following Stream Processor Quick Start Guide

### ISSUE THREAD

**Issue by Meruja** [wso2/product-sp#156]
**Description:**
When we started to follow the Quick start Guide for Stream Processor, the step five does not work. the URL is missing. therefore we can not continue further. The description which is given in the link is not accurate
[https://docs.wso2.com/display/SP400/Quick+Start+Guide](https://docs.wso2.com/display/SP400/Quick+Start+Guide)

**Comment by RukshiW** [comment]
Updated the Quick Start Guide with a different scenario and tested it. The steps given at present work.
