### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Meruja** [wso2/product-sp#164]
**Description:**
https://docs.wso2.com/display/SP400/Deployment+Guide
In the above documentation they have mentioned that the group ID and other configurations required for a clustered set up are edited in the <SP_HOME>/conf/deployment.yaml file. 
But the path should be  **<SP_HOME>/conf/worker/deployment.yaml file.** 
or **<SP_HOME>/conf/manager/deployment.yaml file.** 
I am not sure about the exact path, I hope that it will be correct.

**Comment by suhothayan** [comment]
added content of all possible values
