### ISSUE TITLE
Typos and Grammatical errors

### ISSUE THREAD

**Issue by suganyasuven** [wso2/product-sp#165]
**Description:**
https://docs.wso2.com/display/SP400/Distributed+Deployment
In the above documentation, there are some typos and grammatical errors which need to be corrected.

**Comment by tishan89** [comment]
Below issues were found in the current documentation.
1. It is not clear for the user that they need to add a new datasource(cluster_db) config pointing to shared DB
2. Host value of http interface should be that of the LAN
3. Does not mention about bootstrap and zookeeper URLs
4. Minimum resource count not mentioned
5. Explain about necessity to have unique node ids
6. Explain how to define multiple resource managers

I'll update above details and then let's fix language errors and typos

**Comment by RukshiW** [comment]
Corrected linguistic errors.
