### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Meruja** [wso2/product-sp#167]
**Description:**
https://docs.wso2.com/display/SP400/Creating+a+Distributed+Siddhi+Application
In the above documentation, given links are broken.The links are highlighted below.
A **Siddhi** Application is a combination of multiple Siddhi executional elements. A Siddhi executional element can be a **Siddhi Query** or a **Siddhi Partition.**

**Comment by suhothayan** [comment]
updated the links
