### ISSUE TITLE
Font size is too small in editor

### ISSUE THREAD

**Issue by tharindulak** [wso2/product-sp#168]
**Description:**
In the siddhi editor the font size is too small to read. If a developer need to increase the font size, the browser should be zoomed. 
- It  would be better to allow the developer to adjust font size according to the choice.
- Increasing the default font size also will help the developers  

**Suggested Labels:**
Improvements 

**Suggested Assignees:**
--

**Affected Product Version:**
4.0.0

**Comment by suhothayan** [comment]
Using font size changing feature
