### ISSUE TITLE
Unnecessary button is displayed in the Editor UI with firefox

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#171]
**Description:**
I tried the SP editor with firefox. There is an unnecessary button middle of the screen and it will not disappear.  

![screenshot-2017-11-21 stream processor studio](https://user-images.githubusercontent.com/32059848/33063665-203b3304-cec9-11e7-8094-83cca555eb4e.png)

**Comment by suhothayan** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/668
