### ISSUE TITLE
Issue with suggestions in Siddhi 

### ISSUE THREAD

**Issue by tharindulak** [wso2/product-sp#172]
**Description:**

When I try suggestions in writing Siddhi Queries,
Before selecting the suggestion
![screenshot from 2017-11-21 14-39-02](https://user-images.githubusercontent.com/20821008/33064825-04d6a7de-cecd-11e7-8393-b286d7e8c578.png)
After selecting string as the suggestion 
![screenshot from 2017-11-21 14-39-32](https://user-images.githubusercontent.com/20821008/33064931-5e392f04-cecd-11e7-888e-6aeb4bde9bba.png)
Still it shows up an error.

**Suggested Labels:**
Improvement 

**Affected Product Version:**

4.0.0

**Comment by suhothayan** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/680
