### ISSUE TITLE
Issue with a link to download kafka broker

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#173]
**Description:**
There is a link which can be used to download kafka broker in [this](https://docs.wso2.com/display/SP400/Supporting+Different+Transports#SupportingDifferentTransports-Kafka) documentation which is related to the topic "Receiving and Publishing Events via Kafka Transport", but it does not direct to the correct place.

We can download kafka using [https://kafka.apache.org/downloads]( https://kafka.apache.org/downloads).

**Comment by RukshiW** [comment]
Updated the link as specified.
