### ISSUE TITLE
Issue with the steps mentioned in the doc to enable WSO2 SP to receive and publish events via the Kafka transport

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#174]
**Description:**
In this documentation [https://docs.wso2.com/display/SP400/Supporting+Different+Transports#SupportingDifferentTransports-Kafka](https://docs.wso2.com/display/SP400/Supporting+Different+Transports#SupportingDifferentTransports-Kafka)

The step **2.f** is not needed. If we do so it generates errors
![screenshot-2017-11-22 supporting different transports - stream processor 4 0 0 - wso2 documentation 2](https://user-images.githubusercontent.com/32059848/33118060-9f5b7c94-cf90-11e7-8440-474eee48b831.png)

**Comment by suhothayan** [comment]
Fixed
