### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#175]
**Description:**

In this documentation [https://docs.wso2.com/display/SP400/Supporting+Different+Transports#SupportingDifferentTransports-Kafka](https://docs.wso2.com/display/SP400/Supporting+Different+Transports#SupportingDifferentTransports-Kafka)
![screenshot-2017-11-22 supporting different transports - stream processor 4 0 0 - wso2 documentation 1](https://user-images.githubusercontent.com/32059848/33112090-62a07084-cf77-11e7-8741-55bf3dcacdbd.png)
There is no any directory called libs in the <SP_HOME>, therefore it should be <SP_HOME>/lib.

**Comment by suhothayan** [comment]
fixed all <SP_HOME>/libs to <SP_HOME>/lib
