### ISSUE TITLE
Some steps are missing in the documentation to executue kafka sample

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#176]
**Description:**

 When executing the sample in this doc [https://docs.wso2.com/display/SP400/Sample+0001%3A+Receiving+and+Publishing+Events+via+Kafka+Transport ](https://docs.wso2.com/display/SP400/Sample+0001%3A+Receiving+and+Publishing+Events+via+Kafka+Transport ) , some steps are missing.

**Suggested Labels:**

We need to start zookeeper node using **bin/zookeeper-server-start.sh config/zookeeper.properties** and kafka server node using **bin/kafka-server-start.sh config/server.properties** before start a worker node. It should be mentioned in the documentation.

**Comment by suhothayan** [comment]
Updated the docs with kafka info https://docs.wso2.com/display/SP400/Sample+0001%3A+Receiving+and+Publishing+Events+via+Kafka+Transport
