### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#177]
**Description:**

In this documentation [https://docs.wso2.com/display/SP400/Sample+0001%3A+Receiving+and+Publishing+Events+via+Kafka+Transport](https://docs.wso2.com/display/SP400/Sample+0001%3A+Receiving+and+Publishing+Events+via+Kafka+Transport) <DAS_HOME> should be changed to the <SP_HOME>
![screenshot-2017-11-22 sample 0001 receiving and publishing events via kafka transport - stream processor 4 0 0 - wso2 docum](https://user-images.githubusercontent.com/32059848/33117501-b0429ae4-cf8e-11e7-94fe-82f5b7d9c511.png)
and
![screenshot-2017-11-22 sample 0001 receiving and publishing events via kafka transport - stream processor 4 0 0 - wso2 docum 1](https://user-images.githubusercontent.com/32059848/33117735-93a84356-cf8f-11e7-8957-ef8ae86bbbc8.png)

**Comment by suhothayan** [comment]
Fixed in https://docs.wso2.com/display/SP400/Sample+0001%3A+Receiving+and+Publishing+Events+via+Kafka+Transport
