### ISSUE TITLE
No confirmation when delete a saved feed simulation

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#199]
**Description:**
No confirmation message appeared when user delete a saved feed simulation. If user accidentally click on the button, the configuration getting flushed.
**Suggested Labels:**
Editor

**Suggested Assignees:**
suho@wso2.com

**Affected Product Version:**
wso2sp-4.0.0-beta
**OS, DB, other environment details and versions:**    
Mac OSX
**Steps to reproduce:**
1. Create and save feed simulation
2. Click on right corner more... option and click on Delete
<img width="345" alt="deletefeedsimulation" src="https://user-images.githubusercontent.com/7115693/33285271-cee7dfde-d3d7-11e7-9787-eb0a5552c5f5.png">

**Comment by ramindu90** [comment]
fixed in pr: https://github.com/wso2/carbon-analytics/pull/827
