### ISSUE TITLE
Cannot create a dashboard

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#201]
**Description:**
Once user try to create a dashboard, "Error in adding dashboard!" message appeared but no any errors/exception on server console. Even document doesn't says any pre-configuration to do to work the dashboard.

**Suggested Labels:**
Dashboard

**Suggested Assignees:**
suho@wso2.com

**Affected Product Version:**
wso2sp-4.0.0-beta
**OS, DB, other environment details and versions:**    
Mac OSX
**Steps to reproduce:**
1. Go to portal(http://localhost:9290/portal/) and login
2. Try to create a dashboard

**Related Issues:**

**Comment by suhothayan** [comment]
@NisalaNiroshana is this fixed ?

**Comment by this** [comment]
This is fixed in wso2sp-4.0.0-beta3 pack (carbon-dashboards v4.0.0.beta4). Hence closing.
