### ISSUE TITLE
Portal default ports are incorrect in the doc

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#202]
**Description:**
Dashboard/portal ports are not correct in the documentation [1]
[1] https://docs.wso2.com/display/SP400/Visualization

**Suggested Labels:**
documentation

**Suggested Assignees:**
rukshani@wso2.com

**Affected Product Version:**
wso2sp-4.0.0-beta

**Comment by RukshiW** [comment]
Changed "9090" to "9290", and "9443" to "9643".
