### ISSUE TITLE
Cannot connect to RDBMS store when no password defined 

### ISSUE THREAD

**Issue by tharindulak** [wso2/product-sp#204]
**Description:**
When a developer does not define a password for a particular user it shows up an error as password cannot be empty. If the developer has created users without a password login is not possible.

**Suggested Assignees:**
@gokul 

**Affected Product Version:**

4.0.0 

**Steps to reproduce:**
Make an user without password and try to connect to the user.

**Comment by gokul** [comment]
This needs to be fixed at the extension level. Created https://github.com/wso2-extensions/siddhi-store-rdbms/issues/63.

**Comment by suhothayan** [comment]
https://github.com/wso2-extensions/siddhi-store-rdbms/issues/63 fixed
