### ISSUE TITLE
Update operation is not successful in Hbase

### ISSUE THREAD

**Issue by tharindulak** [wso2/product-sp#213]
**Description:**
After updating values in hbase and solr, it remains same as before.

**Suggested Labels:**
Bugs

**Suggested Assignees:**
@gokul

**Affected Product Version:**
4.0.0
**OS, DB, other environment details and versions:**    
Hbase

**Comment by suhothayan** [comment]
@gokul please verify this issue.

**Comment by sajithshn** [comment]
@tharindulak : was this fixed ?

**Comment by sajithshn** [comment]
Update works when the search key is the Primary Key without a problem. However, if we try to update/search by giving an non existing key there's an exception popping up.

**Comment by tharindulak** [comment]
The issue was fixed. 
In HBase update/search operations work only if the primary key is given.
