### ISSUE TITLE
Editor Issue

### ISSUE THREAD

**Issue by Meruja** [wso2/product-sp#222]
**Description:**
Sometimes we get error when we make some changes in running siddhi application and save it( In my case I have just put a space at the end of the program). And also it says that the particular application successfully deployed and  we could able able to run the siddhi application and get the output.

![issue](https://user-images.githubusercontent.com/28688743/33702565-3aa0daa4-db4a-11e7-8622-f0c7dd469d83.png)

**Comment by ChathurikaA** [comment]
This was fixed by https://github.com/wso2-extensions/siddhi-io-wso2event/pull/42
