### ISSUE TITLE
Startup scripts inside runtimes are not executable

### ISSUE THREAD

**Issue by this** [wso2/product-sp#249]
**Description:**
Startup scripts `carbon.sh` & `carbon.bat` files inside dashboard, editor, manager, worker runtimes are not executable.

`ls -all` command gives following output.
```
-rw-r--r--  1 sajith sajith 6560 Dec 11 22:32 carbon.bat
-rw-r--r--  1 sajith sajith 9670 Dec 11 22:32 carbon.sh
```

**Affected Product Version:**
v4.0.0-beta3

**OS, DB, other environment details and versions:**    
Ubuntu 16.04

**Comment by suhothayan** [comment]
Please validate the issue.

**Comment by Anoukh** [comment]
This is fixed I believe. Seeing the following in update1-snapshot pack and can be executed using ./carbon.sh

```
-rwxr-xr-x 1 anoukh anoukh 6813 දෙසැ  8 19:09 carbon.bat
-rwxr-xr-x 1 anoukh anoukh 9670 දෙසැ 14 23:53 carbon.sh
```

**Comment by suhothayan** [comment]
can you check on SP 4.0.0 as well.

**Comment by Anoukh** [comment]
Checked in SP 4.0.0 and it is also working as expected with correct permissions. I think we can close this issue

**Comment by suhothayan** [comment]
@Anoukh thanks
