### ISSUE TITLE
[DOCS] There is no documentation for widget generation wizard.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/product-sp#258]
**Description:**
[DOCS] There is no documentation for widget generation wizard.

**Suggested Labels:**
Documentation

**Affected Product Version:**
4.0.0

**Comment by suhothayan** [comment]
@CharukaK  is this added?

**Comment by CharukaK** [comment]
@suhothayan yes, it is available in the [docs](https://docs.wso2.com/display/SP400/Generating+Widgets)

**Comment by suhothayan** [comment]
Thanks, hence closing the issue
