### ISSUE TITLE
Error in  Event's Timestamp of  Advanced Configurations of Feed Simulation of Editor in Firefox 

### ISSUE THREAD

**Issue by Irindu** [wso2/product-sp#263]
#**Description:**
Clicking the button Now to give current time stamp and then clicking Done gives NAN rather than the current time stamp in both Starting and Ending time stamp pick panes of Event's Timestamp of  Advanced Configurations of Feed Simulation of Editor
![image](https://user-images.githubusercontent.com/19923256/33991557-0a7880c4-e0f5-11e7-8682-ed34c7408059.png)

![image](https://user-images.githubusercontent.com/19923256/33991630-5a0f6d00-e0f5-11e7-91ec-2749e85a7282.png)

It works on Chrome 63 the issue is only encountered in Firefox 

**Suggested Labels:**
editor,bug 

**Affected Product Version:**
 SP-4.0.0-Beta3

**OS, DB, other environment details and versions:**    
 Ubuntu/Linux, Firefox 57,

**Steps to reproduce:**
1)open a terminal and cd into <SP_HOME>/bin directory and issue./editor.sh to start the editor
2)Open editor on firefox
2)Click on event simulator icon or Ctrl+shift+I to open event simulator 
3)Click on Feed simulator tab of event simulator pane
5)Click create 
6)Click Advanced Configurations 
7) Try to set Event starting timestamp or ending timestamp by clicking calender like button 
8)click now and after that click done 
9)NAN will be retained instead of timestamp value

![image](https://user-images.githubusercontent.com/19923256/33991951-c0b52562-e0f6-11e7-91df-98686fb08778.png)

The issue is also present in Single Simulation windows 
![image](https://user-images.githubusercontent.com/19923256/33992736-c0355e1a-e0f9-11e7-9a1d-e3bbd5a99094.png)

**Comment by suhothayan** [comment]
@erangatl can you verify whether this issue is fixed?

**Comment by erangatl** [comment]
@suhothayan it is reproducible. will look into this
