### ISSUE TITLE
Delete From workspace feautre in File menu of editor not working

### ISSUE THREAD

**Issue by Irindu** [wso2/product-sp#265]
**Description:**
Delete From workspace feautre in File menu of editor not working

![image](https://user-images.githubusercontent.com/19923256/33992279-fadc58f4-e0f7-11e7-9e2a-ad4ef25aa846.png)

It hangs here 

![image](https://user-images.githubusercontent.com/19923256/33992228-cb00c020-e0f7-11e7-80e6-6e09f8bce569.png)

**Suggested Labels:**
Editor,Bug

**Affected Product Version:**
 SP-4.0.0-Beta3

**OS, DB, other environment details and versions:**    
 Ubuntu/Linux, Firefox 57, Chrome 63

**Steps to reproduce:**
1)open a terminal and cd into <SP_HOME>/bin directory and issue./editor.sh to start the editor
2)Launch the editor
3)Click File->Open and select any siddhi app from workspace to open it
4)Try to delete it with Ctrl+D or File-> Delete File 
5)Click Delete again on the delete from workspace window

The Delete Windows Hangs as follows 
![image](https://user-images.githubusercontent.com/19923256/33992447-9cb7bae2-e0f8-11e7-861b-e9f8d3e465a2.png)

**Comment by RAVEENSR** [comment]
Resolved in https://github.com/wso2/carbon-analytics/pull/894
