### ISSUE TITLE
Issue with the editor UI with firefox

### ISSUE THREAD

**Issue by NadeekaHP** [wso2/product-sp#298]
**Description:**
Siddhi apps which are saved in the editor workspace are not shown properly when we use firefox as the browser.

![editoruierror](https://user-images.githubusercontent.com/32059848/34058230-3db1d420-e200-11e7-88d3-8c8f1e338f00.png)

**Comment by suhothayan** [comment]
@erangatl is this fixed?

**Comment by erangatl** [comment]
@suhothayan this reproduces when the app name is too long. will look into this.
