### ISSUE TITLE
Content of the "Key Concepts" page needs to be revisited

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-sp#320]
**Description:**
1. Current content of this page is more like jargon / appendix instead of a key concepts page.
2. If we mentioned about portal/dashboard in this page, then we need to mention on Business Rules, Status Dashboard, SP studio as well.

**Comment by TanyaM** [comment]
As discussed offline let's add Stream Processing and Complex Event Processing definitions into this page

**Comment by suhothayan** [comment]
Added them to the page
