### ISSUE TITLE
How to add a new user/role?

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#323]
**Description:**

Documentation on this is not found.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Niveathika92** [comment]
@nirmal070125 Please find the updated user management documentation [here](https://docs.wso2.com/display/SP400/User+Management)
