### ISSUE TITLE
Improvements to sample memory usage dashboard

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#324]
**Description:**

For portal/dashboards/systemanalytics/overview/memory shall we use some meaningful test data?
typical memory usage graph follows a sawtooth shape. System memory needs to be lower than 100%.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
beta5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by this** [comment]
- Memory usage widget shows actual data of the running server.
- System memory **is** lower than 100%. See below screenshot.
![image](https://user-images.githubusercontent.com/11549922/40103098-f59b3074-5909-11e8-99b2-9acbcb828b0a.png)

**Comment by this** [comment]
This sample dashboard was removed in SP-4.2.0
