### ISSUE TITLE
Why are we bundling the features directory into the product?

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#327]
**Description:**

Is there any reason for bundling features into the SP pack? `wso2/lib/features/`
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by this** [comment]
With C5 Kernel, all the Carbon Features are pack into the `<carbon_home>/wso2/lib/features/` directory. Hence this behavior is expected.
