### ISSUE TITLE
Studio creates a file called String which is of 190+ MB

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#328]
**Description:**

Once you run few simulations etc. on the editor, you see a new file gets created under `wso2/editor/String` which is of 190+ MB and not getting cleaned up.

du -hs wso2/editor/String 
190M	wso2/editor/String

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
beta5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by suhothayan** [comment]
What kind of simulation are you running here ?

**Comment by nirmal070125** [comment]
Random data, feed simulation.

**Comment by dnwick** [comment]
This could not be reproduced. Reducing the severity because editor does not go for production . will check regarding this.

**Comment by this** [comment]
Cannot be re-produced in SP-4.3.0 either. Hence, suggesting to close this issue.
