### ISSUE TITLE
Streams in simulator are not immediately getting updated when siddhi app changed.

### ISSUE THREAD

**Issue by minudika** [wso2/product-sp#329]
**Description:**
When siddhi app is changed and saved during a simulation, the stream attributes shown in the simulator are not getting updated.

**Suggested Labels:**
Bug

**Suggested Assignees:**
@ramindu90 

**Affected Product Version:**
4.0.0-beta5

**Steps to reproduce:**
1. Create a siddhi app, save and run it.
2. Start simulator and select the app and a stream.
3. Change a attribute type of the above selected stream and save the siddhi app.
4. The updated type is not shown in the simulator immediately.

**Comment by suhothayan** [comment]
@ramindu90 is this fixed?

**Comment by ramindu90** [comment]
@suhothayan : fixed with pr: https://github.com/wso2/carbon-analytics/pull/1093
