### ISSUE TITLE
[DOCS] Simulating events using feed simulation should be refactored.

### ISSUE THREAD

**Issue by suganyasuven** [wso2/product-sp#382]
**Description:**
In the Stream Processor Documentation, Simulating events using feed simulation need to be refactored. Screenshots are outdated.

https://docs.wso2.com/display/SP400/Simulating+Multiple+Events+via+CSV+Files

**Suggested Labels:**
Documentation

**Comment by suhothayan** [comment]
@RukshiW Please check on this.

**Comment by RukshiW** [comment]
Updated this page based on the released UI.
