### ISSUE TITLE
[DOCS]Some contents of "Testing a Siddhi Application" need to be changed

### ISSUE THREAD

**Issue by suganyasuven** [wso2/product-sp#383]
**Description:**
Some contents of "Testing a Siddhi Application" need to be changed. It is having the content of the "Debugging Siddhi Applications". But there are some changes need to be done as steps are same except running in a debug mode.

https://docs.wso2.com/display/SP400/Testing+a+Siddhi+Application

1) Introduction part is explaining about debugging. It should be removed.
2) "Running a Siddhi application in the debug mode" need to be changed as "Running a Siddhi application"
3) 4th step under "Running a Siddhi application in the debug mode" is saying to remove source and sink configuration. Here 'map' also should be removed as it is a parameter of source configuration. And if there is no sink configuration, user can't see the event logs, printed on the console. It is better to add "@sink(type='log', prefix='LOGGER')" for the output stream to print the event logs on the console and terminal.
![wso2 sp_modify_siddhi_application](https://user-images.githubusercontent.com/30232477/34194442-ca487264-e57e-11e7-8314-f2bd7f26237e.png)

4)  6th step should be "Click Run => Run" and the message appears in the console below the Siddhi application will be 
![screenshot from 2017-12-20 12-20-19](https://user-images.githubusercontent.com/30232477/34194786-6e42ef88-e580-11e7-84be-6e59b11df5a7.png)
 
**Suggested Labels:**
Documentation

**Comment by suhothayan** [comment]
@RukshiW please check if this is fixed?

**Comment by RukshiW** [comment]
This page is rewritten and reviewed.

**Comment by suhothayan** [comment]
@RukshiW thanks
