### ISSUE TITLE
Contents of "Debugging a Siddhi Application" need to be improved. 

### ISSUE THREAD

**Issue by suganyasuven** [wso2/product-sp#385]
Description:
Contents of "Debugging a Siddhi Application" need to be improved. 

https://docs.wso2.com/display/SP400/Debugging+Siddhi+Applications

1) 4th step under "Running a Siddhi application in the debug mode" is saying to remove source and sink configuration. Here 'map' also should be removed as it is a parameter of source configuration. And if there is no sink configuration, user can't see the event logs, printed on the console. It is better to add "@sink(type='log', prefix='LOGGER')" for the output stream to print the event logs on the console and terminal.
![wso2 sp_modify_siddhi_application](https://user-images.githubusercontent.com/30232477/34195589-64097858-e584-11e7-8f5e-9bbd9865f6c4.png)

2) Message appears in the console below the Siddhi application will be
![screenshot from 2017-12-20 12-54-17](https://user-images.githubusercontent.com/30232477/34195720-05773248-e585-11e7-826a-f668d91e1715.png)

and in another tab following debug screen will be displayed.
![screenshot from 2017-12-20 13-00-46](https://user-images.githubusercontent.com/30232477/34195963-ecd4289e-e585-11e7-959e-f1be3805cb90.png)

3) There are no steps for " how to give the break points for debugging". And also it is better to add "where we can give break points (Eg: it can be given for "from" and "insert into" statements)".

Suggested Labels:
Documentation

**Comment by dnwick** [comment]
Above content should be refactored. I have added the new content . Please see https://docs.wso2.com/display/SP400/Debugging+a+Siddhi+Application
