### ISSUE TITLE
"Configuring Datasources" page needs to be more descriptive  

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-sp#393]
**Description:**
"Configuring Datasources" page [1] needs to contain information on 

- Tested databases and where to find db scripts
- How to set up different databases for each component (Dashboard, Status Dashboard, Business Rules, Common Permission model etc)

[1] https://docs.wso2.com/display/SP400/Configuring+Datasources

**Comment by TanyaM** [comment]
Page [2] has some content related to the above topic. We need to properly group the information in both the pages.

[2] https://docs.wso2.com/display/SP400/Configuring+Database+Queries

**Comment by ksdperera** [comment]
Hi Tanya,
Thanks for informing the issue.
We have added parent page[3], also working on the content improvements as well.

[3] - https://docs.wso2.com/display/SP400/Working+with+Databases

**Comment by suhothayan** [comment]
@ksdperera whats the status of this? Is it done?

**Comment by ksdperera** [comment]
Following datasource information are incomplete we'll update soon:

Carbon Dashboards
Business Rules
IdP Client

**Comment by etalaq** [comment]
To have common DB server for WSO2 products (for implementation of more than one product), better to use prefix for DBs (for example WSO2SP_DASHBOARD_DB) so less manual work to be done by admins on DB servers and on the scripts.

**Comment by ksdperera** [comment]
Hi etalaq,

Thanks for sharing your thought and experience regarding the Datasource naming conventions, actually you don't need to give any specific database name because our internal implementation referred the data source name, not the database name. Since we believe there won't be implication as you can create a database with the desired name.

Furthermore, regarding the data source name, we identified that there is an improvement where we can introduce common prefix as you mentioned, and we have created a new issue for track this task. https://github.com/wso2/product-sp/issues/473

**Comment by ksdperera** [comment]
Regarding the data source documentation task, we can close the issue as we have completed the all the necessary data source related information.

**Comment by luisguillo** [comment]
Hi, can you please provide where to find the database schema creation scripts for DASHBOARD_DB, PERMISSIONS_DB, etc? The documentation only provide queries.yml (i.e.  carbon-analytics-common/components/permission-provider/org.wso2.carbon.analytics.permissions/src/main/resources/queries.yaml) but the queries alone are not useful when there is no schema to work on.

**Comment by ksdperera** [comment]
@luisguillo 
For the 'PERMISSIONS_DB' and DASHBOARD_DB you don't need a database schema creation, it has the required table creation queries for PERMISSIONS_DB[1] and DASHBOARD_DB[2]. And we have tested these two features for the following database types:

**H2, MySQL, Microsoft SQL Server, Oracle**

Could you check our latest release pack?
https://github.com/wso2/product-sp/releases/tag/v4.2.0-M6 

Also, please let us know any database type you are going to use for these two features?
FYI, currently we are working on the Postgres DB support for these two features.

[1] - https://github.com/wso2/carbon-analytics-common/blob/master/components/permission-provider/org.wso2.carbon.analytics.permissions/src/main/resources/queries.yaml
[2] - https://github.com/wso2/carbon-dashboards/blob/master/components/dashboards/org.wso2.carbon.dashboards.core/src/main/resources/sql-queries.yaml

**Comment by luisguillo** [comment]
@ksdperera Thanks. That info solved my problem. The binary 4.1.0 doesn't include the code for the creation of those schemas yet. I solved that manually.
