### ISSUE TITLE
Content is missing for "REST API Guide"

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-sp#394]
**Description:**
Content needs to be updated for "REST API Guide" [1]

[1] https://docs.wso2.com/display/SP400/Stream+Processor+REST+API+Guide

**Comment by TanyaM** [comment]
Some of the content can be found at 
https://docs.google.com/a/wso2.com/spreadsheets/d/1m0sh4DLABCFzCBmjEXtVTrRGM0Mc6lvyYQP6rI99zhQ/edit?usp=sharing

**Comment by ChathurikaA** [comment]
Complete REST API Guide in the product-sp 4.0.0 documentation.
