### ISSUE TITLE
icf-provider.sh inside <carbon_home>/bin directory is not executable

### ISSUE THREAD

**Issue by suganyasuven** [wso2/product-sp#396]
**Description:**
icf-provider.sh inside <carbon_home>/bin directory is not executable.

**Affected Product Version:**
SP Version - wso2sp-4.0.0-RC1

**OS, DB, other environment details and versions:**    
OS: Ubuntu 16.04.3 LTS

**Comment by Anoukh** [comment]
Issue is reported to carbon-kernel wso2/carbon-kernel/1672

**Comment by mohanvive** [comment]
Fixed in https://github.com/wso2/carbon-kernel/commit/4fe52e3f9142c9bfa5a70ce572a21b831c98ebc7 .
