### ISSUE TITLE
Do we have page for  Stream Processor Studio tool which was referenced in Creating a Siddhi Application

### ISSUE THREAD

**Issue by dnwick** [wso2/product-sp#399]
**Description:**
In following description in https://docs.wso2.com/display/SP400/Creating+a+Siddhi+Application 
 "Siddhi applications are files that define the Siddhi logic to process the events sent to WSO2 SP. They are written in the Siddhi Query Language using the Stream Processor Studio tool shipped with WSO2 SP". we reference Stream Processor Studio tool but cannot find a page.

**Comment by TanyaM** [comment]
Let's link it to page [1]
Also let's stick to one term throughout the docs that is "Stream Processor Studio"
Remove all Editor references and rename those.

[1] https://docs.wso2.com/display/SP400/Editor+Overview

**Comment by dnwick** [comment]
Added
