### ISSUE TITLE
Information on how to port offset needs to be added to Admin Guide

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-sp#403]
**Description:**
Documentation contains only information on "Default Ports" and missing information on how to offset different port configurations.

**Comment by ksdperera** [comment]
Added required information for default port offset :

https://docs.wso2.com/display/SP400/Configuring+Default+Ports

**Comment by TanyaM** [comment]
Content added at https://docs.wso2.com/display/SP400/Configuring+Default+Ports
