### ISSUE TITLE
State persistence via DB doesn't work across distributed resource nodes

### ISSUE THREAD

**Issue by nirmal070125** [wso2/product-sp#429]
**Description:**

Team, while testing in K8S, I've faced one issue where if one of the resource nodes goes down (and a new node takes its place) the final DB counts get affected;

*Sample Siddhi app;*
```
@App:name('TestPlan1')
@source(type='kafka', topic.list='test', group.id='1', threading.option='single.thread', bootstrap.servers='kafka-service:9092', @map(type='json'))

define stream TempStream(deviceID long);

@Store(type="rdbms",

       jdbc.url="jdbc:mysql://sp-rdbms:3306/temp?useSSL=false",

       username="root",

       password="root" ,

       jdbc.driver.name="com.mysql.jdbc.Driver")

@PrimaryKey("deviceID")

@index("deviceID")

define table DeviceTempStream (deviceID long, count long);


@info(name = 'query1') @dist(parallel ='1', execGroup='group1')
from TempStream#log('######')
select * insert into TempInternalStream;

@info(name = 'query2') @dist(parallel ='3', execGroup='group2')
partition with ( deviceID of TempInternalStream )
begin
from TempInternalStream#log('@@@@@@')
select deviceID, count(deviceID) as count
update or insert into DeviceTempStream
on DeviceTempStream.deviceID == deviceID
end;
```
*--- before the resource node goes down ---*
mysql> select * from DeviceTempStream;
+----------+-------+
| deviceID | count |
+----------+-------+
|        1 |  9060 |
|        2 |  9063 |
+----------+-------+
2 rows in set (0.00 sec)

*------ once the new node started to function, the same table ----*
mysql> select * from DeviceTempStream;
+----------+-------+
| deviceID | count |
+----------+-------+
|        1 |  9800 |
|        2 |   560 |
+----------+-------+
2 rows in set (0.00 sec)
I have state persistence enabled.

**_Note_** that the count of deviceID=2 is getting reset.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SP 4.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Have a 3 node resource cluster and then kill one node and add a new resource node back and check the DB tables.

**Related Issues:**

**Comment by Anoukh** [comment]
Fixed in PR wso2/siddhi/pull/714
