### ISSUE TITLE
Some external links in "Installing as a Windows Service" page is broken 

### ISSUE THREAD

**Issue by TanyaM** [wso2/product-sp#431]
**Description:**
In the page [1] some external links such as Secure vault link is broken. Please fix those and revisit the content of the page.
[1] https://docs.wso2.com/display/SP400/Installing+as+a+Windows+Service

**Comment by mohanvive** [comment]
@RukshiW , Please fix this doc ASAP.

**Comment by suhothayan** [comment]
@RukshiW this is there for more than a month whats the update on this ?

**Comment by RukshiW** [comment]
Corrected the link. Changed "If the configurations are set properly for YAJSW, you can see a console output similar to the following, and you can now access the Management Console of your product from your web browser via the relevant hosts and ports." as follows:

"If the configurations are set properly for YAJSW, you can see a console output similar to the following, and you can now access the UIs of your product from your web browser via the relevant hosts and ports."
