### ISSUE TITLE
When using the index value as the event timestamp, the simulation fails

### ISSUE THREAD

**Issue by rguikers** [wso2/product-sp#437]
**Description:**
When providing a csv file with a timestamp in it (whatever position), the simulation fails with :

```
Cannot retrieve data elements from line 67 for all indices [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
```
In the line content log I see the the timestamp is not logged : 

```
Line content : [labelA, 0, 25, 87, 29, 39, 9, 8, 13, 3563, 23]
```
So line content has 0..10 indexes, and data element are 0..11 indexes

**Affected Product Version:**
wso2sp-4.0.0

**OS, DB, other environment details and versions:**    
Linux

**Steps to reproduce:**
Just create a simulation file and try to map a timestamp field

**Comment by erangatl** [comment]
@rguikers we have reproduced the issue and working on it.
Meanwhile, as a workaround use the timestamp is in the last position.

**Comment by rguikers** [comment]
@erangatl , Putting the timestamp in the last column gives me the same result. The column gets deleted before being treated as a line item. Hope this gets fixed soon. 

Thanks!

**Comment by mohanvive** [comment]
Closing the issue since the issue is fixed now. 

@rguikers , Thanks for reporting the issue.
