### ISSUE TITLE
Distributed Deployment with WSO2 SP documentation doesn't discuss about replicating siddhi apps with multiple managers

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-sp#458]
**Description:**
The [distributed deployment SP doc page](https://docs.wso2.com/display/SP400/Distributed+Deployment#DistributedDeployment-Configuremanagernodes), doesn't talk how to replicate the siddhi apps with multiple manager nodes. If we front the manager SP nodes with a load balancer, then uploaded siddhi app will be deployed in one node, but for High available manager setup it also needs to be available in another node. In order to obtain such functionality, I believe we need to share the File system. But the doc doesn't mention clearly on what are the possible and recommended options, and steps to perform that.

**Suggested Labels:**
documentation, improvement.

**Comment by Anoukh** [comment]
Details of replicating the siddhi apps in distributed deployment is provided in the documentation on [deploying siddhi apps](https://docs.wso2.com/display/SP400/Deploying+Streaming+Applications). I will do the necessary changes in both docs to be more useful to the user

**Comment by Anoukh** [comment]
I have updated the [doc](https://docs.wso2.com/display/SP400/Distributed+Deployment).
