### ISSUE TITLE
[Event Simulator] Unable to add a new simulation source for an existing Feed Simulation after deleting the Source

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#46]
== Steps to Recreate ==

1. Start the editor, go to event simulator and the select 'Feed Simulation'
2. Create a feed simulation with 'CSV file' as the simulation and save.
3. Click 'Edit' of the created simulation and delete the source by clicking the delete button near 'Source 1 - CSV File'
4. Select 'CSV file' as simulation source and click 'Add New'
5. Try to select 'Siddhi App Name', 'Stream Name' or 'CSV File' from dropdown list

== Actual Result ==

Unable to expand from drop down list to select above fields

== Expected Result ==

Existing Siddhi Apps, streams and csv files should be expand when clicking each drop down list.

![add csv file](https://user-images.githubusercontent.com/8849472/30274188-ee230c84-9719-11e7-8479-a04d11ff0719.png)

**Comment by dnwick** [comment]
this if fixed with PR https://github.com/wso2/carbon-analytics/pull/423 @maneeshaheshan please review and close

**Comment by maneeshaheshan** [comment]
Verified with M12 distribution.
