### ISSUE TITLE
[Event Simulator][Samples] Exception thrown when simulate a single event with event simulator for 'http-io-sample'

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#47]
== Steps to Recreate ==

1. Start the editor, open 'http-io-sample' sample and save it.
2. Go to 'Single Event Simulation' , select the saved siddhi application as 'Siddhi App Name', inputStreamhttp as 'Stream Name' and add a valid Time Stamp (optional)
3. Fill necessary values for event attributes which will be listed after selecting the stream.
4. Start the siddhi application by clicking the 'Start' button.
5. Click 'Send' to send the event

== Actual Result ==

Exception thrown in backend for multiple registered message processors.

`ERROR {org.wso2.carbon.transport.http.netty.internal.HTTPTransportContextHolder} - More than one message processor has registered and cannot proceed with 'null' message processor ID.
ERROR {org.wso2.carbon.transport.http.netty.sender.TargetHandler} - Cannot correlate callback with request callback is null
`

== Expected Result ==

No exception in backend.

![http-io-sample](https://user-images.githubusercontent.com/8849472/30309255-f2873618-97a7-11e7-9890-e5c8596ea2bf.png)

**Comment by suhothayan** [comment]
Fixed in beta
