### ISSUE TITLE
[Improvement] [siddhi-io-file] Error message should be improved which displays for tailing enable by default

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-sp#48]
Description:
Configured source for file type with regex mode as below with 'move.after.process' attribute,
`@source(type='file', mode='regex', begin.regex='event-', end.regex='-event', dir.uri='/home/user/SP_filein', 
action.after.process = 'move', move.after.process = '/home/user/SP_fileout',
@map(type='text'))`

and got an error message like "moveAfterProcess cannot be used when tailing is enabled. Hence stop the siddhi app"

Usability issue: user doesn't get an idea why this error comes since tailing attribute is not present in this config.

Suggestion: Good if error message improved to let the user knows as by default tailing has enabled for regex mode, so that 'MoveAfterProcess' cannot be used

**Comment by suhothayan** [comment]
@minudika Can you fix this in the siddhi-io-file ?

**Comment by minudika** [comment]
Fixed in [siddhi-io-file](https://github.com/wso2-extensions/siddhi-io-file) with the [PR-31](https://github.com/wso2-extensions/siddhi-io-file/pull/31)
