### ISSUE TITLE
[Doc] Insufficient information on Dashboard Authentication Configuration

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#488]
**Description:**
Please provide more information on **Why, When, How** to use this[1] particular configuration.
[1] https://docs.wso2.com/display/SP400/Dashboard+Authentication+Configuration
**Suggested Labels:**
Priority/High, Severity/Critical, Type/Doc

**Comment by pcnfernando** [comment]
The content in the pointed page is invalid. It only describes the local mode. We need to add content for dashboard as in [BusinessRules](https://docs.wso2.com/display/SP400/Configuring+Business+Rules+Manager+Permissions).
@RukshiW please attend to this

**Comment by RukshiW** [comment]
Please check whether the updated information in [1] is correct.

[1] https://docs.wso2.com/display/SP4xx/Dashboard+Authentication+Configuration

**Comment by chaminda** [comment]
We need to mention the file name as well. @pcnfernando  Please check the content on the page.

**Comment by RukshiW** [comment]
Added the file name.

**Comment by Niveathika92** [comment]
@RukshiW Please note that the prerequisite in the page also needs to be updated as in [BusinessRules](https://docs.wso2.com/display/SP400/Configuring+Business+Rules+Manager+Permissions).

We cannot say define the roles in deploymnet.yaml file always, since this depends on the user store the user has configured.

**Comment by RukshiW** [comment]
Updated the Prerequisites section of [1], [2], and [3].

[1] https://docs.wso2.com/display/SP400/Dashboard+Authentication+Configuration
[2] https://docs.wso2.com/display/SP4xx/Dashboard+Authentication+Configuration
[3] https://docs.wso2.com/display/SP410/Dashboard+Authentication+Configuration

**Comment by Niveathika92** [comment]
Closing as per the above comment
