### ISSUE TITLE
[Doc] A section with no description : How to use wso2 securevault: 

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#489]
**Description:**
There is a section heading "How to use wso2 securevault:" in [1] but no any content for it. Please add relevant information.
[1] https://docs.wso2.com/display/SP400/Monitoring+Stream+Processor#MonitoringStreamProcessor-Howtousewso2securevault:

**Suggested Labels:**
Priority/High, Severity/Critical, Type/Doc

**Comment by RukshiW** [comment]
Reviewed and reorganised this documentation. Removed the "How to use wso2 secure vault" sub headingand added it as a link in the 2nd step of the "Configuring cluster credentials" sub heading.
