### ISSUE TITLE
Default config.json should be included with sample processors and directories for type 'analytics-streams'

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#491]
**Description:**
In default **config.json**[1] should be included with sample processors and directories for type 'analytics-streams' . Currently there is only the log-file type in the config.json.

[1] <SP_HOME>/wso2/tools/identity-anonymization-tool-1.1.2/conf/config.json

**Suggested Labels:**
Priority/High, Type/Improvement, 

**Affected Product Version:**
wso2sp-4.0.0-update8

**Comment by pcnfernando** [comment]
As we do not have persisted streams in SP, 'analytics-streams' processor config is not valid.
