### ISSUE TITLE
Mentioning the default configuration directory of the tool. 

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#492]
**Description:**
In the table(please refer highlighted text in below image), It would be better to mention the default config location below the description in [1]

![image](https://user-images.githubusercontent.com/7115693/37133522-d30d53ce-22b9-11e8-91bf-ac30f7963c9a.png)

[1] https://docs.wso2.com/display/SP4xx/Removing+Personally+Identifiable+Information+via+the+Forget-me+Tool

**Suggested Labels:**
Type/Doc Type/Improvement

**Comment by RukshiW** [comment]
Corrected as follows:

- In [1], mentioned the following.
"If you do not specify a value for this option, the <DAS_HOME>/repository/components/tools/identity-anonymization-tool-x.x.x/conf directory (which is the default configuration directory of the tool) is used."

- In [2]. mentioned the following.
"If you do not specify a value for this option, the <SP_HOME>/wso2/tools/identity-anonymization-tool-x.x.x/conf directory (which is the default configuration directory of the tool) is used."

[1] https://docs.wso2.com/display/DAS3xx/General+Data+Protection+Regulations+for+WSO2+Data+Analytics+Server
[2] https://docs.wso2.com/display/SP4xx/Removing+Personally+Identifiable+Information+via+the+Forget-me+Tool

**Comment by chaminda** [comment]
Verified on docs
