### ISSUE TITLE
[Improvement] [UI] Better if cancelling the editing of an existing feed simulation without any changes won't give a pop up to confirm

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#50]
== Steps to Recreate ==

1. Start the editor, go to event simulator and the select 'Feed Simulation'
2. Create a feed simulation with 'CSV file' as the simulation and save.
3. Click 'Edit' of the created simulation and press 'Cancel' to exit without doing any modifications.

== Actual Result ==

Popup will be displayed by asking to confirm where to discard the changes or not even there're no changes. 

![feed simulation cancel](https://user-images.githubusercontent.com/8849472/30329444-e7431720-97ef-11e7-9822-f9e03020fb09.png)

== Suggestion ==

Better if the pop up won't display if the user haven't done any changes for simulation.

**Comment by dnwick** [comment]
@maneeshaheshan fixed in PR https://github.com/wso2/carbon-analytics/pull/426 please review and close

**Comment by maneeshaheshan** [comment]
Hi @dnwick ,

Existing from the editing mode of a simulation by clicking the close button at top right corner was fixed. But existing by clicking the 'Cancel' button needs to be fix.

**Comment by mohanvive** [comment]
@dnwick can you check this and confirm.

**Comment by dnwick** [comment]
This fixed now
