### ISSUE TITLE
Provide documentation on how to enable jdbc reporting

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-sp#515]
**Description:**
In order to generate relevant graphs on details on JDBC reporting in status dashboard(CPU usage, memory usage etc...) we have to enable the JDBC Reporter in the <SP_HOME>/conf/worker/deployment.yaml file. Documentation on this is unavailable. Add the relevant documentation in [here](https://docs.wso2.com/display/SP400/Configuring+the+Status+Dashboard)

This is the relevant configuration placed under wso2.metrics.jdbc: ->  reporting: ->  jdbc: ->  enabled: 

#Enable JDBC Reporter
      enabled: true

**Suggested Labels:**
Type/Documentation Priority/Normal

**Suggested Assignees:**
@RukshiW 

**Affected Product Version:**
Product-SP 4.1.0 RC1

![error](https://user-images.githubusercontent.com/19996612/37485283-ff4409b8-28b0-11e8-9b2f-9b08c36fb5cd.png)

**Comment by RAVEENSR** [comment]
And also it is better to add the relevent yaml configuration part and describe the default values after in a table.

wso2.metrics.jdbc:
  #Data Source Configurations for JDBC Reporters
  dataSource:
    # Default Data Source Configuration
    - &JDBC01
      # JNDI name of the data source to be used by the JDBC Reporter.
      # This data source should be defined in a *-datasources.xml file in conf/datasources directory.
      dataSourceName: java:comp/env/jdbc/WSO2MetricsDB
      # Schedule regular deletion of metrics data older than a set number of days.
      # It is recommended that you enable this job to ensure your metrics tables do not get extremely large.
      # Deleting data older than seven days should be sufficient.
      scheduledCleanup:
        #Enable scheduled cleanup to delete Metrics data in the database.
        enabled: false
        #The scheduled job will cleanup all data older than the specified days
        daysToKeep: 7
        #This is the period for each cleanup operation in seconds.
        scheduledCleanupPeriod: 86400

Add the above part before the table shown below.
![errorr2](https://user-images.githubusercontent.com/19996612/37485849-a8b7277c-28b2-11e8-8302-0aa09fb9d138.png)

**Comment by RukshiW** [comment]
Corrected this for SP 4.0.0, 4.1.0 and 4.x.x.

[1] https://docs.wso2.com/display/SP400/Configuring+the+Status+Dashboard
[2] https://docs.wso2.com/display/SP410/Configuring+the+Status+Dashboard
[3] https://docs.wso2.com/display/SP4xx/Configuring+the+Status+Dashboard

**Comment by sajithshn** [comment]
This is added to the documentation.
