### ISSUE TITLE
Portal logo should be linked to the portal url itself.

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#518]
**Description:**
Portal logo(see the screen below) has not been linked to the portal (https://localhost:9643/portal). due to this user has no easy way(other than the back button) to come back to the portal home page when go deep inside the sections.

![image](https://user-images.githubusercontent.com/7115693/37507624-8540ec48-2915-11e8-8029-434a4977aeb6.png)

**Comment by this** [comment]
Issue moved to the correct repo. See https://github.com/wso2/carbon-dashboards/issues/878.
