### ISSUE TITLE
[Event Simulator] No Date Pickers for Starting Event's Timestamp and Ending Event's Timestamp when editing an existing Feed Simulation

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#52]
== Steps to Recreate ==

1. Start the editor, go to event simulator and the select 'Feed Simulation'
2. Create a feed simulation by adding valid values for 'Starting Event's Timestamp' and 'Ending Event's Timestamp' with 'CSV file' as the simulation and save.
3. Click 'Edit' of the created simulation.

== Actual Result ==

 There's no date picker to choose date and time for time stamp field. 

== Expected Result ==

User should be able to modify 'Starting Event's Timestamp' and 'Ending Event's Timestamp' by picking a date and time from date picker.

![no date picker when editing](https://user-images.githubusercontent.com/8849472/30362973-12f9aad2-987c-11e7-8443-e4c05b188f19.png)

**Comment by dnwick** [comment]
@maneeshaheshan fixed in PR https://github.com/wso2/carbon-analytics/pull/426 please review and close

**Comment by maneeshaheshan** [comment]
Verified with latest build.
