### ISSUE TITLE
Cookie Policy and Privacy Policy redirected to non-existing page in the portal.

### ISSUE THREAD

**Issue by chaminda** [wso2/product-sp#521]
**Description:**
Cookie Policy and Privacy Policy redirected to non-existing page in the portal login[1].
[1]https://localhost:9643/portal/login

**Affected Product Version:**
4.1.0-RC2

**Comment by pcnfernando** [comment]
Checked the links from poral/login. It directs to the correct Cookie Policy and Privacy Policy pages.
