### ISSUE TITLE
Review added content on QSG

### ISSUE THREAD

**Issue by tishan89** [wso2/product-sp#528]
**Description:**
Added a what's new section on quick start guide for continuity of documentation.

> What's next?
> Learn more about Siddhi and how it can solve your problems : Tutorials
> 
> Learn about how to develop, deploy and monitor Siddhi applications : User Guide
> 

**Affected Product Version:**
4.0.0 4.1.0

**Comment by RukshiW** [comment]
Modified this section as follows:
"What's next?
Learn more about Siddhi and how it can be helpful in your user scenarios: Tutorials
Learn how to develop, deploy and monitor Siddhi applications: User Guide"
