### ISSUE TITLE
[Event Simulator] Warning log thrown for not having timestamp attribute or time interval even it was configured in Feed Simulation Configuration

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#53]
== Steps to Recreate ==

1. Start the editor, go to event simulator and the select 'Feed Simulation'
2. Create a feed simulation by adding valid values for 'Starting Event's Timestamp', 'Ending Event's Timestamp' and 'Time Interval' with 'CSV file' as the simulation and save.

== Actual Result ==

A warning log thrown in backend for not having timestamp attribute or time interval.

``WARN {org.wso2.carbon.event.simulator.core.internal.generator.csv.core.CSVEventGenerator} - Either timestamp attribute or time interval is required for CSV simulation of stream 'inputStreamHttp'. Time interval will be set to 1 second for source configuration : {"fileName":"tEstcEv.csv","delimiter":",","timeInterval":"1000","simulationType":"CSV_SIMULATION","streamName":"inputStreamHttp","isOrdered":true,"siddhiAppName":"io-sample"}
``

== Expected Result ==

No warn log should be printed since the necessary fields were filled accurately. Even though warn message mentioned about missing 'TimeStamp Attribute', there's no such attribute to add for simulation configs.

![with time interval and timestamps](https://user-images.githubusercontent.com/8849472/30368232-3746aa9a-988e-11e7-8578-2d90c5cf1c4f.png)

**Comment by dnwick** [comment]
this fixed with PR https://github.com/wso2/carbon-analytics/pull/423

**Comment by maneeshaheshan** [comment]
Verified with latest build.
