### ISSUE TITLE
Displaying Sinks And Sources In The SP Editor Design View

### ISSUE THREAD

**Issue by ramindu90** [wso2/product-sp#536]
**Description:**
Currently, the design view of the SP Editor does not identify sinks and sources as different components and considers them as part of the stream. 

**Goals**
This feature will display sinks and sources as separated nodes in the design view of the Stream Processor Editor and link them with the necessary edges to the streams that they belong too.

**Affected Product Version:**
SP 4.1.0

**Comment by sajithshn** [comment]
This is fixed
