### ISSUE TITLE
[Event Simulator] Duplicate field reference for Time Interval and TimeStamp Interval in Simulation Configuration file

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#54]
== Steps to Recreate ==

1. Create a feed simulation by adding valid values 'Time Interval' and 'TimeStamp Interval' with 'CSV file' as the simulation and save.
2. Go to [SP_HOME]/deployment/simulation-configs and open the simulation file which created early.

== Actual Result ==

Both 'Time Interval' and 'TimeStamp Interval' fields refer to same filed as 'timeInterval' in simulation config.

**In File**

![timeinterval 1](https://user-images.githubusercontent.com/8849472/30370543-8f54f00a-9895-11e7-9956-f7828ffb5b2e.png)

**In UI**

![time interval and timestamp interval](https://user-images.githubusercontent.com/8849472/30370565-9f9ae3d4-9895-11e7-9448-11f4b576f3be.png)

== Expected Result ==

Referred fields in simulation config file for both attributes should be map to different attributes.

**Comment by dnwick** [comment]
this if fixed with PR https://github.com/wso2/carbon-analytics/pull/423 @maneeshaheshan please review and close

**Comment by maneeshaheshan** [comment]
Verified with latest build.
