### ISSUE TITLE
Editor: Cannot save a Siddhi App which doesn't include @App:name() annotation

### ISSUE THREAD

**Issue by Niveathika92** [wso2/product-sp#550]
**Description:**
$subject. This does not produce any errors. However, this the Save to Workspace dialog does not close either.
NB: when the /*@App:name('')*/ is added inside a comment, the Siddhi app is saved with the first line changed to  @App:name('') /*   */

**Suggested Labels:**
Editor, Bug

**Suggested Assignees:**
@erangatl 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
SP 4.1.0

**Steps to reproduce:**
1. Go to http://localhost:9390/editor
2. Open a new file
3. Add a siddhi app without @app:name()
4. Try to save

**Related Issues:**

**Comment by NisalaNiroshana** [comment]
This is fixed in new 4.2.0 beta version. Hence closing the issue.
