### ISSUE TITLE
Widget are not get loaded

### ISSUE THREAD

**Issue by Meruja** [wso2/product-sp#554]
**Description:**
When we click to see the widget of twitter analytics dashboard., it does not show the widgets and gets load. Issue on this [PR](https://github.com/wso2/product-sp/pull/553)

**Steps to reproduce:**
1.Start the dashboard
2.Click on the link to open portal dashboard
3.Click 'view' icon in the Twitter-Analytics dashboard

**Issue**
![react-error](https://user-images.githubusercontent.com/28688743/39501911-21294558-4ddb-11e8-90f9-dbf209c841a9.png)

**Comment by this** [comment]
As per mail thread [[Dev] Avoid loading multiple copies of React](https://markmail.org/message/x6qu4dqfxrx5wt24), this issue should be fixed [carbon-dashboards](https://github.com/wso2/carbon-dashboards)
