### ISSUE TITLE
[status-dashboard] - Siddhi App Component Statistics 'value' column not update correctly 

### ISSUE THREAD

**Issue by ksdperera** [wso2/product-sp#555]
**Description:**
As shown in the image even though the graph for each type has historical data, 'value' column not update correctly.

<img width="1328" alt="screen shot 2018-05-02 at 5 23 56 pm" src="https://user-images.githubusercontent.com/5366557/39522139-06be43a4-4e2f-11e8-8c60-eb4df8c4e07c.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SP-4.1.0

**OS, DB, other environment details and versions:**    
H2, MySQL, MSSQL and Oracle

**Steps to reproduce:**
1) Enable the Metrics feature in the dashboard and worker runtime.
2) Deploy the following siddhi application in worker runtime.
```
@App:name('TestSiddhiApp')
@app:statistics(reporter = 'jdbc')

@source(type = 'http',
        receiver.url='http://localhost:8006/productionStream',
        basic.auth.enabled='false',@map(type='json', @attributes( name = '$.item.id', amount = '$.item.amount')))
define stream SweetProductionStream (name string, amount double);

@sink(type='log')
define stream LowProductionAlertStream (name string, amount double);

-- passthrough data in the SweetProductionStream into LowProducitonAlertStream
@info(name='query1')
from SweetProductionStream
select *
insert into LowProductionAlertStream;
```
3) Login to the status dashboard and add the worker runtime details.
4) Nevigate to the Siddhi App statistics page
5) Publish the data using follwoing curl command
```
curl -X POST -d "{\"item\": {\"id\":\"Sugar\",\"amount\": 300.5}}"  http://localhost:8006/productionStream --header "Content-Type:application/json" -k
```
6) Analyze values in Siddhi App Component Statistics table

**Related Issues:**

**Comment by Yasara123** [comment]
Fixed in https://github.com/wso2/carbon-analytics/issues/1236
