### ISSUE TITLE
[Bug] Twitter Analytics Solution Drill Down pages are not rendering.

### ISSUE THREAD

**Issue by ksdperera** [wso2/product-sp#592]
**Description:**
After the new Dashboard dependency upgrading, there is an issue when rendering the Tweeter analytics drill down pages:

/portal/dashboards/twitteranalytics/EmotionAnalysis
/portal/dashboards/twitteranalytics/TweetAnalysis

Browser Error logs:

```
u.errors.ConfigurationError {name: "Configuration Error", message: "Unknown component "undefined"", node: undefined}
```
<img width="1435" alt="screen shot 2018-06-02 at 12 02 31 am" src="https://user-images.githubusercontent.com/5366557/40857514-0630cf06-65f9-11e8-8e55-07b6188764f4.png">

**Suggested Labels:**
WSO2-SP-4.2.0-alpha

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NisalaNiroshana** [comment]
Resolved with #929
