### ISSUE TITLE
Adding Drag and Drop functionality to Siddhi Editor

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-sp#613]
**Description:**
With the introduction of drag & drop feature to the Siddhi Editor, there will be two views for the user, to create a Siddhi app.
In addition to the currently existing _**Code View**_ - where the user can type in and create a Siddhi app, the _**Design View**_ is introduced - where the user can generate a Siddhi app by dragging & dropping Siddhi elements from the tool bar, configuring them, and connecting them.
Both the _design view_ and _code view_ of a Siddhi app are inter-changeable.

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@senthuran16
@RAVEENSR 
@moizalicious 

**Affected Product Version:**
WSO2SP_4.2.0_beta

**Comment by NisalaNiroshana** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1290
