### ISSUE TITLE
Wrong links in the README.md

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-sp#644]
**Description:**
In the README.md under **Documentation** the link to  `WSO2 Documentation site for WSO2 SP` points to a non-existent page.

Also some of the links points to documentation of an older release (4.0.0).

**Suggested Labels:**
Documentation

**Comment by suhothayan** [comment]
Thanks for reporting. 
Fixed the doc links https://github.com/wso2/product-sp/pull/665
