### ISSUE TITLE
[Documentation] Issues in tutorial "Integrating Data Stores"

### ISSUE THREAD

**Issue by Ambujaa10** [wso2/product-sp#667]
**Description:**

Two Issues are encountered in SP tutorial - Integrating Datastores. The database name has to be changed to SweetFactoryDB and the jdbc url has to be jdbc:mysql://localhost:3306/SweetFactoryDB. 
http://0.0.0.0:9763/ShipmentHistoryApp/RawMaterialsStream \ has to be changed to http://0.0.0.0:8280/ShipmentHistoryApp/RawMaterialsStream \ under c URL commands.
**Suggested Labels:**

Documentation
**Suggested Assignees:**

@RukshiW 
**Affected Product Version:**
4.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RukshiW** [comment]
Made the corrections described above.

**Comment by Niveathika92** [comment]
Closing as per the above comment.
Doc [Integrating Datastores](https://docs.wso2.com/display/SP4xx/Integrating+Datastores)
