### ISSUE TITLE
Two active nodes in HA

### ISSUE THREAD

**Issue by dzatloukal** [wso2/product-sp#669]
**Description:**
Running two Stream Processors in HA cluster, after started is corectly selected one node as active and the second node as passive. But after few time, passive node become active for no reason, because there is no error on active node. So I have two active nodes, seems like a bug. You can see screenshot posted below.
[Screenshot of two active nodes](https://abload.de/img/sphabpjhg.png)

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
SP 4.1.0
**OS, DB, other environment details and versions:**    
Windows
**Steps to reproduce:**

**Related Issues:**

**Comment by Niveathika92** [comment]
@dzatloukal Could you add the configurations of both nodes to get a better idea of the deployment?

**Comment by dzatloukal** [comment]
@Niveathika92 Ok.
**First node**
cluster.config:
  enabled: true
  groupId: sp
  coordinationStrategyClass: org.wso2.carbon.cluster.coordinator.rdbms.RDBMSCoordinationStrategy
  strategyConfig:
    datasource: WSO2_CLUSTER_DB
    heartbeatInterval: 1000
    heartbeatMaxRetry: 10
    eventPollingInterval: 1000

deployment.config:
  type: ha
  liveSync:
    enabled: true
    advertisedHost: nameOfFirstServer
    advertisedPort: 9090
    username: admin
    password: admin
  outputSyncInterval: 1000
  stateSyncGracePeriod: 10000
  sinkQueueCapacity: 20000
  sourceQueueCapacity: 20000
  retryAppSyncPeriod: 10000

**The second node configuration is similiar except advertisedHost, where is nameOfSecondServer.**

For cluster DB we are using MSSQL database.

**Comment by Niveathika92** [comment]
@dzatloukal When this issue was occurring, was the database connection lost in any instance?

**Comment by dzatloukal** [comment]
@Niveathika92 Yes. We turned on logging from coordination class and realized, that both nodes are active when connection to DB is lost, after reconnection one node become coordination leader, the second become coordination member, but the member wil not change state back to passive. Seems that there is new thread with same [issue](https://github.com/wso2/product-sp/issues/756)

**Comment by pcnfernando** [comment]
Fixed with [#1403](https://github.com/wso2/carbon-analytics/pull/1403)
