### ISSUE TITLE
Improve Storage Integration Doc

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#670]
**Description:**
The current doc[1] misses the content on how storage can be used in various ways. 
IMO the main page should be discussing the following in brief as separate subsections : 

1. Defining Data Stores - explain how to define Event Table and DB backed up tables (more details should go to a different page)
2. Manipulating Stored Data Using Streams - Talk about Joining with Streams, contains check using "in" keyword, updating, and deleting data using streams (more details should go to a different page)
3. Manipulating Stored Data Using RestAPIs - Talk about accessing data from Tables, Inserting, deleting and updating using REST APIs (more details should go to a different page)

I think we should have a sperate page for each of these providing detail information. 

[1]https://docs.wso2.com/display/SP420/Storage+Integration

**Comment by Niveathika92** [comment]
@RukshiW, we also have released siddhi-store-rdbms(v4.0.22) through which data can be retrieved/manipulated from multiple event tables.

**Comment by RukshiW** [comment]
Updated the Storage Integration section. Please check [1].

[1] https://docs.wso2.com/display/SP4xx/Storage+Integration
