### ISSUE TITLE
Unicode characters are not getting encoded in Siddhi Drag & Drop Editor

### ISSUE THREAD

**Issue by senthuran16** [wso2/product-sp#675]
**Description:**
Unicode Characters are not getting encoded in Siddhi Drag & Drop Editor.
Please refer topic **Unicode Strings** under https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa for the fix

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**
@RAVEENSR 

**Affected Product Version:**
wso2_sp_4.2.0

**Comment by dnwick** [comment]
Fixed in https://github.com/wso2/carbon-analytics/pull/1589
