### ISSUE TITLE
[Documentation] UX Issues in tutorial "Creating a Simple Siddhi Application"

### ISSUE THREAD

**Issue by erangatl** [wso2/product-sp#676]
**Description:**
In the "Creating a Simple Siddhi Application" tutorial it is suggested to write the Siddhi Application > Run Editor > Open a new file > and copy paste the Siddhi Application.

Instead, we should promote users to write the Siddhi Application in the Editor itself.

[https://docs.wso2.com/display/SP420/Creating+a+Simple+Siddhi+Application](url)

**Suggested Labels:**
Documentation, Editor, Improvement, UX

**Suggested Assignees:**
@RukshiW 

**Affected Product Version:**
4.2.0-rc2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RukshiW** [comment]
Updated this tutorial to instruct the user to compose the Siddhi application in the Stream Processor Studio itself.
