### ISSUE TITLE
When one value is no the chart its not displayed correctly. 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#686]
**Description:**
Single value colum table is not displayed corretly. 

<img width="1440" alt="screen shot 2018-07-06 at 11 40 15 pm" src="https://user-images.githubusercontent.com/3785208/42394652-89816d76-8178-11e8-8fe7-8242e45cf3a6.png">

**Comment by dilini-muthumala** [comment]
Fix published to npm hence closing the issue.
