### ISSUE TITLE
Make current events as default in Query creation, in the graphical editor 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#690]
**Description:**
currently, all events is used as default, 
also don't show "current event" as text when generating the query from the graphical editor 
<img width="430" alt="screen shot 2018-07-09 at 1 43 31 am" src="https://user-images.githubusercontent.com/3785208/42423812-2e08d6d0-831e-11e8-8541-40cc85de3822.png">

**Comment by tishan89** [comment]
Fixed in 4.3.0
