### ISSUE TITLE
Editor feed simulation edit view error

### ISSUE THREAD

**Issue by erangatl** [wso2/product-sp#696]
**Description:*
When a feed simulation is saved and if you try to edit it back, the UI renders different than initial.

**Suggested Labels:**
Editor, Bug, 

**Suggested Assignees:**
@dnwick  @ramindu90 

**Affected Product Version:**
v4.2.0-rc2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a feed simulation and save
Try to edit it back

**Comment by tishan89** [comment]
Fixed hence resolving
