### ISSUE TITLE
Portal dashboard click option does not work in Firefox browser

### ISSUE THREAD

**Issue by mohanvive** [wso2/product-sp#712]
**Description:**
Portal dashboard click option does not work in Firefox browser. 

See the image below,
![click](https://user-images.githubusercontent.com/7523274/42911155-7c7da55c-8b07-11e8-9d20-fc17051ded1d.png)

Firefox version is given below,
![firefox version](https://user-images.githubusercontent.com/7523274/42911200-a5c259c6-8b07-11e8-9bc4-7ddd7152593d.png)

**Comment by NisalaNiroshana** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/pull/981
