### ISSUE TITLE
Have "current events" as the default selection for the queries in graphical editor

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#716]
**Description:**
Currently all events is selected by default. 
Please change that to "current events" 
<img width="1157" alt="screen shot 2018-07-19 at 9 23 24 am" src="https://user-images.githubusercontent.com/3785208/42956748-a180dc60-8b35-11e8-9d2b-51dc0a09f475.png">

Also when the code view is generated from the design view don't add the "current events" to the query string if thats selected. Because thats the default. 
<img width="412" alt="screen shot 2018-07-19 at 9 23 48 am" src="https://user-images.githubusercontent.com/3785208/42956758-a772798a-8b35-11e8-9460-8a095f1c0072.png">

**Comment by PradeepaJey1** [comment]
Fixed in this PR https://github.com/wso2/carbon-analytics/pull/1382
