### ISSUE TITLE
Twitter Analytics solution - Popular Tweets widget does not update

### ISSUE THREAD

**Issue by erangatl** [wso2/product-sp#720]
**Description:**
Popular Tweets widget does not update for Siddhi app changes, always show #amazon

![image](https://user-images.githubusercontent.com/20179540/43121163-7384554a-8f3a-11e8-988f-d8ed05d9c437.png)

**Suggested Labels:**
Bug,

**Suggested Assignees:**
@lasanthaS 

**Affected Product Version:**
4.2.0

**Comment by Niveathika92** [comment]
Adding @ruwiniwj

**Comment by Niveathika92** [comment]
@erangatl A refresh button was added to the popular tweets widget.

![screenshot from 2019-01-02 11-40-15](https://user-images.githubusercontent.com/27669465/50581826-58831100-0e83-11e9-8e98-46c85c27835a.png)

**Comment by Niveathika92** [comment]
This is fixed, however the refresh icon must be clicked....
![screenshot from 2019-01-02 11-40-15](https://user-images.githubusercontent.com/27669465/50582498-07761b80-0e89-11e9-8935-c95a0839a263.png)
