### ISSUE TITLE
[Editor] Saving siddhi files on a remote Linux instance accessed via a Windows instance

### ISSUE THREAD

**Issue by pcnfernando** [wso2/product-sp#732]
**Description:**
When we start Stream Processor editor in a remote linux server and access it via a Windows instance, the siddhi file created would be saved on SP_Pack_HOME/wso2/editor/deployment  and the name of the siddhi file would be appended with "workspace\\" at the front.

**Suggested Labels:**
Editor, Remote Access

**Suggested Assignees:**
@erangatl 

**Affected Product Version:**
Stream Processor v4.2.0

**OS, DB, other environment details and versions:**    
Remote OS : Ubuntu 16.04
Local OS: Windows 10

**Steps to reproduce:**

1. Start Stream Processor in editor profile in a Linux remote instance.
2. Access the editor from a Windows instance.
3. Create Siddhi file and save it using the name **TestApp.siddhi**.
4. View SP_HOME/wso2/editor/deployment directory.
5. The sidhdi file will be saved with the name **workspace\TestApp.siddhi**

**Comment by dnwick** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/1380
