### ISSUE TITLE
Store API does not order events when ORDER BY clause is used

### ISSUE THREAD

**Issue by nihlaakram** [wso2/product-sp#733]
**Description:**
When retrieving data via the Store API, if the query contains an ORDER BY clause, the data in retrieved is not ordered. However, after multiple requests, the data can be obtained in an orderly manner.

**Suggested Labels:**
Type/Bug

**Comment by pcnfernando** [comment]
Fixed with [#893](https://github.com/wso2/siddhi/pull/893)
