### ISSUE TITLE
Performance test results do not get written to the output file

### ISSUE THREAD

**Issue by miyurud** [wso2/product-sp#741]
**Description:**
When we use the WSO2 SP throughput extension in a Siddhi application to measure its performance, we do not get the performance values saved in the output file.

**Suggested Labels:**
Performance Measurement

**Affected Product Version:**
SP 4.x

**OS, DB, other environment details and versions:** 
  Ubuntu 16.04

**Comment by tishan89** [comment]
Close as per above comment
