### ISSUE TITLE
Changing the 'on' value in the query doesn't get affected when using the rest API

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-sp#743]
following two queries return the same result when used with the rest api

`from ApiUserPerAppAgg on gatewayType=='SYNAPSE' within '2018-08-** **:**:**' per 'months' SELECT sum(totalRequestCount) as sum`

`from ApiUserPerAppAgg on gatewayType=='MICRO' within '2018-08-** **:**:**' per 'months' SELECT sum(totalRequestCount) as sum`

Restarting the server would give the correct result

**Comment by Niveathika92** [comment]
This is a Siddhi level bug, the following siddhi test case is also failing
https://github.com/Niveathika92/siddhi/commit/bee6bdcd77fa991cf645bb8a8af6d901cea7f947
