### ISSUE TITLE
'order by' not working

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-sp#753]
Seems like 'order by' clause does not work when using the rest api. Following is a sample query 

`{"appName" : "APIM_ABNORMAL_REQUEST_PATTERN", "query" : "from ApimAllAlert SELECT type, tenantDomain, message, severity, alertTimestamp  order by alertTimestamp asc;"}`

same result is given after changing the asc/desc

**Comment by Niveathika92** [comment]
As a temporary workaround, could you use the following query?

`from ApimAllAlert SELECT * order by alertTimestamp asc`
