### ISSUE TITLE
[HA] 2 workers becomes active-active when db connection resets

### ISSUE THREAD

**Issue by ramindu90** [wso2/product-sp#756]
**Description:**
If the database goes down, both nodes becomes active-active. But even the database becomes back to normal and the 2 workers gets connected again, one doesnt go back to passive

**Affected Product Version:**
4.1.0

**Steps to reproduce:**
1. Setup SP HA setup
2. Start the 2 nodes
3. Take down or take down the connection to the db for both nodes
4. reconnect the database again

**Comment by this** [comment]
The above linked PRs have been merged _after the release of SP-4.2.0_, hence the issue is **not fixed** in that.

**Comment by this** [comment]
Reopening as the issue is still reproducible in SP-4.3.0.

**Comment by this** [comment]
Closing as issue is fixed in SP-4.3.0 GA.
