### ISSUE TITLE
[Status Dashboard] JsonSyntaxException is thrown when manager is added

### ISSUE THREAD

**Issue by pcnfernando** [wso2/product-sp#759]
**Description:**
Below exception is thrown when the manager is added to the status dashboard.
This happens when **cluster.config** property in manager's deployment.yaml is set to false.

![image](https://user-images.githubusercontent.com/15815199/44332040-b5f46380-a488-11e8-927f-b8c865e462d9.png)

**Suggested Labels:**
Status Dashboard, manager

**Suggested Assignees:**

**Affected Product Version:**
v4.2.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04

**Steps to reproduce:**

1. Get a SP 4.2.0 fresh pack
2. Start the manager profile.
3. Start the dashboard profile.
4. Access monitoring dashboard and add the manager.

**Related Issues:**

**Comment by tishan89** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1409
