### ISSUE TITLE
[Status Dashboard] When clicked on the manager thumbnail gives an internal error

### ISSUE THREAD

**Issue by erangatl** [wso2/product-sp#760]
**Description:**
When clicked on the manager thumbnail, gives an internal error

![image](https://user-images.githubusercontent.com/20179540/44333759-682e2a00-a48d-11e8-88f4-e2ba067aceca.png)

![image](https://user-images.githubusercontent.com/20179540/44333677-28674280-a48d-11e8-8509-91cc518ad3f4.png)

**Suggested Labels:**
Bug, Critical

**Affected Product Version:**
4.2.0

**Related Issues:**
#759

**Comment by tishan89** [comment]
Fixed with above PR
