### ISSUE TITLE
No documentations for deployment

### ISSUE THREAD

**Issue by ThisaruGuruge** [wso2/product-sp#767]
**Description:**
> There are multiple deployment directories in the product and there is no guide / documentation for to which directory to copy siddhi apps, etc.

**Suggested Labels:**
> Documentation, Enhancement

**Suggested Assignees:**
> N/A

**Affected Product Version:**
> N/A

**OS, DB, other environment details and versions:**    
> N/A

**Steps to reproduce:**
> N/A

**Related Issues:**
> N/A

**Comment by RukshiW** [comment]
Added documentation on the four profiles of WSO2 SP and how to deploy Siddhi applications in them [1]. Please check and let me know if any changes are required.

[1] https://docs.wso2.com/display/SP4xx/WSO2+Stream+Processor+Profiles

**Comment by ThisaruGuruge** [comment]
This looks fine.
