### ISSUE TITLE
RabbitMQ sample README is not descriptive enough. (sample 41)

### ISSUE THREAD

**Issue by RAVEENSR** [wso2/product-sp#77]
Installing the rabbitmq server has several steps and needed to install other needed dependencies as well. While installing these dependencies conflicts occur. README file needed to be more descriptive.

**Comment by tishan89** [comment]
@sivaramya Please look into this

**Comment by sivaramya** [comment]
fixed in Improved 0041 - RabbitMQ readme file #82
