### ISSUE TITLE
[ kubernetes-sp ] Http source in siddhi application requires receiver.url IP to be set 0.0.0.0 with https in kubernetes distribution

### ISSUE THREAD

**Issue by Ketharan** [wso2/product-sp#784]
**Description:**

When running the distributed deployment pattern of wso2sp-4.2.0 in kubernetes , the http source configuration of the deployed siddhi application requires the receiver.url to be set to  `receiver.url='https://0.0.0.0:xxxx/xxxxxxxxxxxxx'`

> 
Here the protocol and IP required to be set to https and 0.0.0.0 respectively. Else errors 502 /308 thrown when curl request sent from remote.

 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2sp-4.2.0

**OS, DB, other environment details and versions:**    
GCP's kubernetes engine, Distributed deployment pattern wso2sp-4.2.0

**Steps to reproduce:**
Deploy a siddhi application which contains an http source with a different receiver url in the kubernetes cluster. Send curl request to that source from remote.

**Comment by pcnfernando** [comment]
With docker port forwarding, there are two network namespaces you need to keep track of. The first is inside your container. If you listen on localhost inside the container, nothing outside the container can connect to your application. That includes blocking port forwarding from the docker host and container to container networking. 
So unless your container is talking to itself, you always listen on 0.0.0.0 with the application you are running inside the container.
