### ISSUE TITLE
Changing the port offset doesn't affect https ports

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/product-sp#786]
changing the port offset doesn't affect the https ports. it starts with 9443 . same goes for 9090 port as well. thrift port changes with the offset

**Comment by this** [comment]
```yaml
  ports:
      # port offset
    offset: 0
```
Above configuration does not work. Instead you need to manually change port to offset.
- https://github.com/wso2/product-sp/blob/v4.3.0-rc3/modules/distribution/carbon-home/conf/editor/deployment.yaml#L40
- https://github.com/wso2/product-sp/blob/v4.3.0-rc3/modules/distribution/carbon-home/conf/worker/deployment.yaml#L42
- https://github.com/wso2/product-sp/blob/v4.3.0-rc3/modules/distribution/carbon-home/conf/manager/deployment.yaml#L40
- https://github.com/wso2/product-sp/blob/v4.3.0-rc3/modules/distribution/carbon-home/conf/dashboard/deployment.yaml#L459
