### ISSUE TITLE
Editor Design Document contains older screen shots

### ISSUE THREAD

**Issue by dnwick** [wso2/product-sp#813]
Following link https://docs.wso2.com/display/SP420/Working+with+the+Design+View contains older screen shots. Can we please update them

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RukshiW** [comment]
Replaced the images and changed the related text in [1] and [2]. Added descriptions for Pattern and Sequence. Please review.

This correction was made for SP versions 4.2.0, 4.3.0, and 4.x.x.

[1] https://docs.wso2.com/display/SP430/Working+with+the+Design+View
[2] https://docs.wso2.com/display/SP430/Creating+a+Siddhi+Application

**Comment by tishan89** [comment]
Closing as per above comment
