### ISSUE TITLE
Unable to perform json request through siddhi app

### ISSUE THREAD

**Issue by Lasith650** [wso2/product-sp#814]
**Description:**
I am trying to connect to the github api through a siddhi app using the bellow code,

@App:name("SiddhiAppGitHub2")
@App:description("Description of the plan")

@sink(type='http-request' , publisher.url='https://api.github.com/repos/wso2/product-sp/releases', method='GET', sink.id='releases_data', @map(type='json')) 
define stream GitReleaseInputStream(state string);
  

@source(type='http-response' , sink.id='release_data', http.status.code='200', @map(type='json', @attributes(state='$.assets.[0].state'))) 
define stream GitReleaseCatchInputStream(state string);

@sink(type='log') 
define stream GitReleaseOutputStream(state string);

from GitReleaseCatchInputStream
select state
insert into GitReleaseOutputStream;

But I am not getting a response. Bellow is the response I received when I requested through "Postman"

 
![screenshot from 2018-09-13 15-06-39](https://user-images.githubusercontent.com/23395897/45480589-f3d26800-b766-11e8-929e-408171f3d1d3.png)

**Comment by this** [comment]
Please move this issue to https://github.com/wso2/siddhi/issues repo.

**Comment by Lasith650** [comment]
moved to
https://github.com/wso2-extensions/siddhi-io-http/issues/80#issue-363445629
