### ISSUE TITLE
[Editor] An error message appears at an incorrect stage

### ISSUE THREAD

**Issue by RukshiW** [wso2/product-sp#822]
**Description:**
1. Start creating a new Siddhi application in the Design View.
2. Drag and drop the Source icon to add a source.
3. In the **Source Configuration** form, enter a name for the source in the **Name** field and click **Save**.

An error appears  to indicate that the source is not connected to a stream.
Since the user is allowed to connect the source to a stream only after a name is entered in the form, is it correct for this error to appear at this stage?

**Affected Product Version:**
Sp 4.3.0

![error_for_source](https://user-images.githubusercontent.com/26239861/45606222-e536ca00-ba60-11e8-8808-7ee35bcf27cb.gif)

**Comment by tishan89** [comment]
Fixed with above referenced PR
