### ISSUE TITLE
[Editor] OpenFile explorer fails to show files in workspace folder

### ISSUE THREAD

**Issue by pcnfernando** [wso2/product-sp#827]
**Description:**
When an already started pack is copied to another machine and when we try to open a Siddhi file within the workspace directory, the OpenFile explorer fails to show the files in the workspace directory.
![image](https://user-images.githubusercontent.com/15815199/45995863-7e945a80-c0b7-11e8-9565-6d67637875da.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 SP v4.2.0
First started on Linux 16.04.
Copied pack to Windows 10.

**OS, DB, other environment details and versions:**    
Chrome Browser

**Steps to reproduce:**

**Related Issues:**

**Comment by pcnfernando** [comment]
This issue is related to Windows OS. In the fresh pack itself, the OpenFile explorer fails to show the files in the workspace directory.

**Comment by pcnfernando** [comment]
Same issue is reproduced in ImportSample explorer as well.

**Comment by dnwick** [comment]
I just tried in a fresh sp 4.2.0 in windows and it works fine.

**Comment by pcnfernando** [comment]
This issue can be reproduced doing the following steps.

- Start editor on Linux machine.
- Copy the same pack to a Windows machine.
- Start the editor.

**Comment by tishan89** [comment]
@erangatl Can you please follow up this?

**Comment by erangatl** [comment]
Tested on a wso2sp-4.4.0-m12 pack and works fine.

**Comment by lasanthaS** [comment]
@erangatl If so, can we close this issue?

**Comment by erangatl** [comment]
> @erangatl If so, can we close this issue?

Yes, we can close this.
