### ISSUE TITLE
[Documentation] HTTP Analytics screenshot to be updated in SP 4.3.0 doc space

### ISSUE THREAD

**Issue by Niveathika92** [wso2/product-sp#834]
**Description:**
$subject in https://docs.wso2.com/display/SP430/HTTP+Analytics

**Comment by mohanvive** [comment]
@RukshiW Can you please fix this?

**Comment by RukshiW** [comment]
Corrected this. Can you please check? https://docs.wso2.com/display/SP430/HTTP+Analytics

**Comment by Niveathika92** [comment]
@RukshiW Looks good
