### ISSUE TITLE
[Ubuntu16-04]The file is saved in the wrong location, and the workspace cannot open the saved files

### ISSUE THREAD

**Issue by qwyinxiang** [wso2/product-sp#846]
**Description:**
On Ubuntu16-4, I deploy wso2-sp, and runs ./wso2sp-4.2.0/bin/editor.sh file.

Then I visit  http://UbuntuServerIP:9390/editor.

I opened servial sample siddhi files on the welcome page and saved them,but I cannot see any files when I clicked the workspace tab.
![image](https://user-images.githubusercontent.com/31084798/46845639-d8fb1e00-ce0e-11e8-9d39-9e9ae48f1fe9.png)

I opened the path of the workspace on "/wso2sp-4.2.0/wso2/editor/deployment/workspace".
The directory is emply.
![image](https://user-images.githubusercontent.com/31084798/46845508-5bcfa900-ce0e-11e8-85e5-e5cf4396f821.png)

Then I return to the parent directory on "/wso2sp-4.2.0/wso2/editor/deployment/", I saw my saved files.
![image](https://user-images.githubusercontent.com/31084798/46845716-237c9a80-ce0f-11e8-9ba1-b6ef199e546f.png)

**Comment by Niveathika92** [comment]
Hi @qwyinxiang,
This bug was an identified in SP 4.2.0, this is due to accessing the editor from a Windows machine even though the server is started in Ubuntu. We have fixed it in the latest SP4.3.0 [release.](https://github.com/wso2/product-sp/releases/tag/v4.3.0)

**Comment by qwyinxiang** [comment]
oh, I tried the SP4.3.0, it works well, thanks a lot for your patience.
