### ISSUE TITLE
[Dashboard] Aggregations not supported in Siddhi App Component Statistics

### ISSUE THREAD

**Issue by shehan360** [wso2/product-sp#848]
**Description:**
Having an aggregation in the Siddhi app causes an exception to be thrown in dashboard node. Other statistics wont be displayed either till the aggregation is removed.

![screenshot from 2018-10-16 11-38-37](https://user-images.githubusercontent.com/33398983/46998028-06add300-d13f-11e8-86d3-532abf1ec3f4.png)

**Affected Product Version:**
4.3.0

**Steps to reproduce:**
1. Have a siddhi app with aggregations in worker node
2. Run dashboard
3. Go to monitoring and go the node
4. Select the Siddhi App from Siddhi Applications table

**Comment by Niveathika92** [comment]
Closing as this is fixed with the above PR
