### ISSUE TITLE
Metrics are written in the same file when  calling Performance extension multiple times.

### ISSUE THREAD

**Issue by SaranganJ** [wso2/product-sp#853]
[**Description:**](url)

If we initialize the performance extension at multiple places in the Siddhi code (In normal deployment mode) then each performance call will write the metric to the same file.To differentiate multiple performance calls we need to insert an id parameter for the extension

**Affected Product Version:**
WSO2-SP-4.3

**OS, DB, other environment details and versions:**   
Ubuntu-18.04

**Comment by Niveathika92** [comment]
Throughput extension can only be called once in a single flow if used multiple times, the event count is incremented n times rather than 1.

**Comment by Niveathika92** [comment]
@SaranganJ As discussed during the code review, the bug given in the description is not applicable. Update the issue accordingly.

**Comment by SaranganJ** [comment]
Updated.

**Comment by Niveathika92** [comment]
Closing this as the fix is merged
