### ISSUE TITLE
[Dashboard ] No option to remove an existing page in Dashboard

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-sp#86]
== Steps to Recreate ==

1. Create a dashboard by providing a name and url.
2. Open dashboard in design view, go to available listed pages and select a page

== Actual Result ==

There's no option to remove the page.

![no option set as default](https://user-images.githubusercontent.com/8849472/30833645-8289c9a4-a26d-11e7-967d-c6d1cc39b150.png)

== Expected Result ==

There should be an option to remove a selected page

**Comment by TanyaM** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/issues/633
