### ISSUE TITLE
[Worker] Deploying WSO2 EI Analytics solution

### ISSUE THREAD

**Issue by amerireza** [wso2/product-sp#867]
**Description:**
Can not see data when in the dashboard of SP for EI Analytics.

**Suggested Labels:**

**OS, DB, other environment details and versions:**    
using WSO2 SP 4.3.0 and WSO2 EI 6.4.0, over ubuntu 16.04lts

**Steps to reproduce:**

I configured the EI for sending statistics and tracing data to SP, here is the configs:
1. changed truststore field in `<CARBON_HOME>/conf/data-bridge/data-agent-config.xml` file and point it to WSO2 SP `client-truststore.jks` file for both `Thrift` and `Binary` agents.
2. set the ip of SP and 7611 as port in **"receiverURL"** field of files 
- `<CARBON_HOME>/repository/deployment/server/eventpublishers/MessageFlowConfigurationPublisher.xml`

- `<CARBON_HOME>/repository/deployment/server/eventpublishers/MessageFlowStatisticsPublisher.xml`

3. enabled the mediation statistics and message tracing in the synapse.properties file in <EI_HOME>/conf/synapse.properties.
4. start SP worker with wso2 carbon server with `type: wso2-ei-analytics`.
5. **PROBLEM** is that I can see no data in https://WSO2-SP-IP:9643/portal/dashboards/eianalytics and there is no error in worker logs.

**Comment by isharailanga** [comment]
Hi @amerireza 
Have you enabled mediation statistics and message tracing by configuring the <EI_HOME>/conf/synapse.properties file, if not you can follow [this](https://medium.com/@isharailanga/configure-wso2-sp-for-wso2-ei-for-ei-analytics-8e7d8ef128fe) and configure that file.

**Comment by Niveathika92** [comment]
Hi @amerireza, Did you check the database? Are the events persisted and not seen in the portal?

**Comment by amerireza** [comment]
Hi @Niveathika92
I don't know how to check it. I haven't change any database configurations in SP yet.

**Comment by amerireza** [comment]
Hi @isharailanga ,
I had done that when I wrote this issue, I have enabled the mediation statistics and message tracing in the synapse.properties file.
I also I have used your post to do this.

Since I have no errors in ESB or SP logs. I think the problem is in the SP side.

**Comment by Niveathika92** [comment]
@amerireza I am closing this issue as the bug is fixed.
