### ISSUE TITLE
Too many open files when using Editor 

### ISSUE THREAD

**Issue by suhothayan** [wso2/product-sp#874]
**Description:**
When using the editor and implementing some logic in Siddhi, too many open files issue is popping up, and it needs a restart. 

**Affected Product Version:**
SP 4.3

**Comment by Niveathika92** [comment]
Seems to be a result of https://github.com/wso2-extensions/siddhi-io-http/issues/92

**Comment by Niveathika92** [comment]
Also noticed file leak when using Importing samples

**Comment by Niveathika92** [comment]
Importing sample file leak is fixed with https://github.com/wso2/carbon-analytics/pull/1487

**Comment by Niveathika92** [comment]
This was released with version [v4.4.0-m10](https://github.com/wso2/product-sp/releases/tag/v4.4.0-m10)
