### ISSUE TITLE
Editor Usability Improvements and Bug fixes

### ISSUE THREAD

**Issue by NisalaNiroshana** [wso2/product-sp#882]
**Description:**
Editor Usability Improvements and Bug fixes

- Dotted line between HTTP request sink and HTTP response source
- [editor] Generate default XML, JSON sample events for stream definitions
- Sample explorer needs to be improved (full-text search )
- Highlight the changing element in the design view

**Suggested Labels:**
@bug

**Suggested Assignees:**
@dnwick @PradeepaJey1 @kts-desilva @NisalaNiroshana 

**Affected Product Version:**
SP 4.3.0

**Comment by tishan89** [comment]
@NisalaNiroshana Can we close this issue?

**Comment by NisalaNiroshana** [comment]
There are multiple usability improvements which resolved these UI/UX issues. So we can close this one.
