### ISSUE TITLE
SP is not started correctly without the DB connections

### ISSUE THREAD

**Issue by NisalaNiroshana** [wso2/product-sp#902]
**Description:**
SP 4.3.0 is not started correctly without the DB connection. Although the DB connection is available after some time, SP will not recover from its state. SP 4.2.0 is working correctly.

**Suggested Labels:**
@Bug

**Suggested Assignees:**

**Affected Product Version:**
SP 4.3.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Shutdown the DB server and start the SP worker

**Related Issues:**
NA

**Comment by minudika** [comment]
Resolved hence closing
