### ISSUE TITLE
Document about Fault Streams

### ISSUE THREAD

**Issue by sajithshn** [wso2/product-sp#917]
**Description:**
Document about Fault streams in confluent doc space. 

Please refer https://github.com/siddhi-io/siddhi/blob/master/docs/documentation/siddhi-4.0.md#fault-streams

**Comment by RukshiW** [comment]
Added the documentation in [1]. Please review.

[1] https://docs.wso2.com/display/SP4xx/Fault+Handling

**Comment by mohanvive** [comment]
Documentation looks good hence closing the issue..
