### ISSUE TITLE
Error when re-importing a dashboard

### ISSUE THREAD

**Issue by erangatl** [wso2/product-sp#954]
**Description:**
Error when re-importing a dashboard

![image](https://user-images.githubusercontent.com/20179540/55155892-81fbc200-517e-11e9-84c6-cbc70304b21b.png)

**Suggested Labels:**
Priority/Normal, Severity/Minor, Type/Bug

**Suggested Assignees:**
@lasanthaS 

**Affected Product Version:**
wso2sp-4.4.0-alpha-SNAPSHOT

**Steps to reproduce:**
1. Export a analytics dashboard.
2. Delete the exciting dashboard.
3. Import the exported dashboard.

**Comment by niveathika** [comment]
Fixed with https://github.com/wso2/carbon-dashboards/pull/1161
