### ISSUE TITLE
[Editor] shortcut for Deploy feature is Shift + D

### ISSUE THREAD

**Issue by Niveathika92** [wso2/product-sp#965]
**Description:**
$subject. This makes it impossible to type upper case D in siddhi apps. The shortcut should be "Ctrl+Shift+D" 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by erangatl** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1632

**Comment by lasanthaS** [comment]
As per the above comment the issue is fixed, hence closing.

**Comment by LakshanSS** [comment]
Since Ctrl+Shift+D was used for both Debug and Deploy, I added Ctrl+Shift+P as the keyboard shortcut for Deploy in https://github.com/wso2/carbon-analytics/pull/1646
