### ISSUE TITLE
[Improvement] [Editor] Showing logs in the console

### ISSUE THREAD

**Issue by niruhan** [wso2/product-sp#99]
**Description:**
It would be easier for a developer if he can see the logs in the console of Stream Processor Studio itself rather than having to go and look at the terminal.

When I was adding content to Quick Start Guide, in order to convince a user that the query actually works I directed him/her to log the output stream using newly added log sink. The logs will be shown in the terminal he/she used to start the editor. It really is an inconvenience and it would be much much better if he/she can see the logs in the console itself.

**Related Issues:**
[Improvement] [Editor] Showing events from a user selected stream in the console #100

**Comment by suhothayan** [comment]
Fixed in beta
