### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Yahya222** [wso2/product-sp#993]
I'am using the stream processor in order to filter out so messages which are coming at or rate of 200 msg per second. 
I'am using partition and a #window.unique:time. After running for minutes i always run into memory leak problem. After that the memory usage goes up until it caps at around 40 % and then the stream processor craches.
i Get this error 
[2019-05-01_00-41-06_201] ERROR {io.netty.util.ResourceLeakDetector} - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information. (Encoded)

**Comment by niveathika** [comment]
@Yahya222, Does the partition key verifies significantly?

**Comment by Yahya222** [comment]
@niveathika assuming you mean varies yes they do thank you for the insight i just swapped the partition parameter and the window parameter because the window parameter has much less variation and i have no more problems.

**Comment by niveathika** [comment]
@Yahya222, It is a known issue in Siddhi 4.x that partition cannot handle a huge amount of variation in the keys. As partitions cannot be cleaned after expiry time. It is best to not use partition if the values you expect will not be finite. 

You can raise questions on [siddhi-user group](https://groups.google.com/forum/#!forum/siddhi-user) or an issue in https://github.com/siddhi-io/siddhi to get recommendation on handling various use cases efficiently.

**Comment by Yahya222** [comment]
Thanks a lot , there is one remaining problem if you have any insights it would be helpful. I am using the wso2 stream processor on a cloud server. Due the the fact that i'am still in testing phase i would rather deploy the editor so i can edit elsewhere. I have noticed that whenever i stop the app the memory usage do not go down ? is that also a know issue ?

**Comment by niveathika** [comment]
@Yahya222 No, we have not noticed this. As you mentioned the siddhi app contains partitions and windows only?

**Comment by Yahya222** [comment]
Thanks everything seems to be working fine for now. I'll open another issue as soon as i get more insights .
