### ISSUE TITLE
Allow design view to save unicode characters

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-sp#997]
**Description:**
The following issue is fixed in source view. It should be fixed in Design view as well. 
https://github.com/wso2/product-sp/issues/675

**Suggested Labels:**
priority/high
type/bug

**Suggested Assignees:**
@suhothayan 

**Affected Product Version:**
wso2sp-4.3.0

**Related Issues:**
https://github.com/wso2/product-sp/issues/675
https://github.com/wso2/carbon-analytics/pull/1589

**Comment by dnwick** [comment]
fixed in https://github.com/wso2/carbon-analytics/pull/1683
